/**
 * Export PDF Button Component
 * Universal PDF export for dashboards and reports
 *
 * FEATURES:
 * - Click-to-export functionality
 * - Loading states
 * - Error handling
 * - Customizable appearance
 */

"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { pdfExportService } from "@/lib/services/export/pdfExportService";
import type { PDFExportOptions } from "@/lib/services/export/pdfExportService";

interface ExportPDFButtonProps {
  title: string;
  subtitle?: string;
  data: any;
  filename?: string;
  compact?: boolean;
  variant?: "primary" | "secondary" | "outline";
  onExportComplete?: (pdfUrl: string) => void;
  onExportError?: (error: string) => void;
}

export default function ExportPDFButton({
  title,
  subtitle,
  data,
  filename,
  compact = false,
  variant = "primary",
  onExportComplete,
  onExportError,
}: ExportPDFButtonProps) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);

    try {
      const options: PDFExportOptions = {
        title,
        subtitle,
        data,
        branding: {
          companyName: "BlueDXP Platform",
          footer: "Generated by BlueDXP Platform",
        },
      };

      const result = await pdfExportService.exportDashboard(options);

      if (result.success && result.pdfUrl) {
        // In production, would trigger actual download
        console.log("PDF generated:", result.pdfUrl);

        // Simulate download
        const link = document.createElement("a");
        link.href = result.pdfUrl;
        link.download =
          filename || `${title.toLowerCase().replace(/\s+/g, "-")}.pdf`;
        // Note: In production, the pdfUrl would be a real file URL
        // For now, just log it
        console.log("Download link created:", link.download);

        onExportComplete?.(result.pdfUrl);

        // Show success message
        alert(`✅ PDF export ready! File: ${link.download}`);
      } else {
        throw new Error(result.error || "Failed to generate PDF");
      }
    } catch (error) {
      console.error("Export error:", error);
      const errorMsg =
        error instanceof Error ? error.message : "Failed to export PDF";
      onExportError?.(errorMsg);
      alert(`❌ Error: ${errorMsg}`);
    } finally {
      setExporting(false);
    }
  };

  const getVariantClasses = () => {
    switch (variant) {
      case "primary":
        return "bg-blue-600 hover:bg-blue-700 text-white";
      case "secondary":
        return "bg-gray-600 hover:bg-gray-700 text-white";
      case "outline":
        return "border-2 border-blue-600 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20";
      default:
        return "bg-blue-600 hover:bg-blue-700 text-white";
    }
  };

  if (compact) {
    return (
      <button
        onClick={handleExport}
        disabled={exporting}
        className={`px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 text-sm ${getVariantClasses()}`}
      >
        {exporting ? (
          <>
            <i className="ri-loader-4-line animate-spin" />
            Exporting...
          </>
        ) : (
          <>
            <i className="ri-file-pdf-line" />
            Export PDF
          </>
        )}
      </button>
    );
  }

  return (
    <motion.button
      onClick={handleExport}
      disabled={exporting}
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      className={`px-4 py-2 rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 font-medium ${getVariantClasses()}`}
    >
      {exporting ? (
        <>
          <i className="ri-loader-4-line animate-spin text-lg" />
          Generating PDF...
        </>
      ) : (
        <>
          <i className="ri-file-pdf-line text-lg" />
          Export to PDF
        </>
      )}
    </motion.button>
  );
}
