"use client";

import { useState, useEffect } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useViewContext } from "@/contexts/ViewContextProvider";
import PageTemplate from "@/components/PageTemplate";
import AutomatedInsights from "@/components/intelligent-orchestration/AutomatedInsights";
import CustomerSelector from "@/components/multi-tenant/CustomerSelector";
import ViewScopeSelector from "@/components/role-based/ViewScopeSelector";
import { generateMultiTenantCustomers } from "@/utils/mockDataGenerators";
import {
  AutomatedInsight,
  AutomatedReport,
} from "@/types/intelligentOrchestration";
import { orchestrationEngine } from "@/data/intelligentOrchestrationEngine";

export default function AutomatedInsightsPage() {
  const { user } = useAuth();
  const { context } = useViewContext();
  const [customers] = useState(() =>
    generateMultiTenantCustomers(20, user?.tenantId || "tenant-1"),
  );
  const [insights, setInsights] = useState<AutomatedInsight[]>([]);
  const [reports, setReports] = useState<AutomatedReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Generate mock insights and reports
  useEffect(() => {
    const generateMockData = async () => {
      setIsLoading(true);

      // Generate mock insights
      const mockInsights: AutomatedInsight[] = [];
      const insightTypes: AutomatedInsight["insightType"][] = [
        "PERFORMANCE",
        "OPTIMIZATION",
        "RISK",
        "OPPORTUNITY",
        "ANOMALY",
        "TREND",
      ];
      const severities: AutomatedInsight["severity"][] = [
        "INFO",
        "LOW",
        "MEDIUM",
        "HIGH",
        "CRITICAL",
      ];

      for (let i = 0; i < 25; i++) {
        const insightType =
          insightTypes[Math.floor(Math.random() * insightTypes.length)];
        const severity =
          severities[Math.floor(Math.random() * severities.length)];
        const generatedAt = new Date(
          Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000,
        );
        const acknowledged = Math.random() > 0.3;

        mockInsights.push({
          id: `insight-${i + 1}`,
          insightType,
          title: `${insightType} Insight ${i + 1}`,
          description: `Automated ${insightType.toLowerCase()} insight generated by AI analysis`,
          severity,
          confidence: 70 + Math.random() * 25,
          data: {
            metric: "performance",
            value: Math.random() * 100,
            trend: ["up", "down", "stable"][Math.floor(Math.random() * 3)],
          },
          recommendations: [
            "Review process flow",
            "Optimize resource allocation",
            "Monitor closely",
          ],
          actions: [
            "Schedule review meeting",
            "Update process documentation",
            "Implement optimization",
          ],
          generatedAt: generatedAt.toISOString(),
          expiresAt: new Date(
            generatedAt.getTime() + 30 * 24 * 60 * 60 * 1000,
          ).toISOString(),
          acknowledged,
          acknowledgedBy: acknowledged
            ? `User ${Math.floor(Math.random() * 10) + 1}`
            : undefined,
          acknowledgedAt: acknowledged
            ? new Date(
                generatedAt.getTime() + Math.random() * 24 * 60 * 60 * 1000,
              ).toISOString()
            : undefined,
          impact: {
            duration: Math.random() * 3600 * 2,
            cost: Math.random() * 5000,
            quality: Math.random() * 20,
            compliance: Math.random() * 15,
            revenue: Math.random() * 10000,
          },
        });
      }

      setInsights(mockInsights);

      // Generate mock reports
      const mockReports: AutomatedReport[] = [
        {
          id: "report-1",
          name: "Daily Performance Report",
          description: "Daily performance metrics and KPIs",
          reportType: "PERFORMANCE",
          schedule: {
            frequency: "DAILY",
            time: "09:00",
            timezone: "UTC",
          },
          recipients: [
            {
              id: "rec-1",
              type: "ROLE",
              identifier: "WAREHOUSE_HEAD",
              channel: "EMAIL",
            },
          ],
          format: "PDF",
          sections: [
            {
              id: "section-1",
              title: "Performance Metrics",
              type: "METRIC",
              dataSource: "performance-metrics",
              order: 1,
            },
            {
              id: "section-2",
              title: "KPI Dashboard",
              type: "CHART",
              dataSource: "kpi-data",
              visualization: {
                chartType: "BAR",
                config: {},
              },
              order: 2,
            },
          ],
          filters: [],
          isActive: true,
          lastGenerated: new Date(
            Date.now() - 24 * 60 * 60 * 1000,
          ).toISOString(),
          nextGeneration: new Date(
            Date.now() + 24 * 60 * 60 * 1000,
          ).toISOString(),
        },
        {
          id: "report-2",
          name: "Weekly Compliance Report",
          description: "Weekly compliance and SLA status report",
          reportType: "COMPLIANCE",
          schedule: {
            frequency: "WEEKLY",
            time: "09:00",
            dayOfWeek: 1, // Monday
            timezone: "UTC",
          },
          recipients: [
            {
              id: "rec-2",
              type: "ROLE",
              identifier: "BUSINESS_DEVELOPMENT_MANAGER",
              channel: "EMAIL",
            },
          ],
          format: "EXCEL",
          sections: [
            {
              id: "section-3",
              title: "SLA Compliance",
              type: "TABLE",
              dataSource: "sla-compliance",
              order: 1,
            },
          ],
          filters: [],
          isActive: true,
          lastGenerated: new Date(
            Date.now() - 7 * 24 * 60 * 60 * 1000,
          ).toISOString(),
          nextGeneration: new Date(
            Date.now() + 7 * 24 * 60 * 60 * 1000,
          ).toISOString(),
        },
        {
          id: "report-3",
          name: "Monthly Financial Report",
          description: "Monthly financial performance and cost analysis",
          reportType: "FINANCIAL",
          schedule: {
            frequency: "MONTHLY",
            time: "09:00",
            dayOfMonth: 1,
            timezone: "UTC",
          },
          recipients: [
            {
              id: "rec-3",
              type: "ROLE",
              identifier: "SYSTEM_ADMIN",
              channel: "EMAIL",
            },
          ],
          format: "PDF",
          sections: [
            {
              id: "section-4",
              title: "Financial Summary",
              type: "METRIC",
              dataSource: "financial-data",
              order: 1,
            },
          ],
          filters: [],
          isActive: true,
          lastGenerated: new Date(
            Date.now() - 30 * 24 * 60 * 60 * 1000,
          ).toISOString(),
          nextGeneration: new Date(
            Date.now() + 30 * 24 * 60 * 60 * 1000,
          ).toISOString(),
        },
      ];

      setReports(mockReports);
      setIsLoading(false);
    };

    generateMockData();
  }, []);

  const handleInsightAcknowledge = (insightId: string) => {
    setInsights((prev) =>
      prev.map((i) =>
        i.id === insightId
          ? {
              ...i,
              acknowledged: true,
              acknowledgedAt: new Date().toISOString(),
              acknowledgedBy: user?.name || "Current User",
            }
          : i,
      ),
    );
  };

  const handleReportGenerate = (reportId: string) => {
    setReports((prev) =>
      prev.map((r) =>
        r.id === reportId
          ? {
              ...r,
              lastGenerated: new Date().toISOString(),
            }
          : r,
      ),
    );
    // In a real app, this would trigger report generation
    alert(`Generating report: ${reports.find((r) => r.id === reportId)?.name}`);
  };

  const stats = [
    {
      label: "Total Insights",
      value: insights.length,
      icon: "ri-lightbulb-line",
      tooltip: "Total AI-generated insights",
      trend: "up" as const,
    },
    {
      label: "Acknowledged",
      value: insights.filter((i) => i.acknowledged).length,
      icon: "ri-checkbox-circle-line",
      tooltip: "Acknowledged insights",
      trend: "up" as const,
    },
    {
      label: "Critical Insights",
      value: insights.filter((i) => i.severity === "CRITICAL").length,
      icon: "ri-alert-line",
      tooltip: "Critical priority insights",
      trend: "neutral" as const,
    },
    {
      label: "Automated Reports",
      value: reports.length,
      icon: "ri-file-chart-line",
      tooltip: "Automated report configurations",
      trend: "neutral" as const,
    },
  ];

  return (
    <PageTemplate
      title="Automated Insights"
      description="AI-generated insights and automated reports. Intelligent analysis, predictive recommendations, and automated report generation for data-driven decision making."
      shortDescription="AI-generated insights and automated reports"
      icon="ri-sparkling-line"
      systemInfo={{
        sap: "Business Intelligence",
        oracle: "Analytics & Insights",
        manhattan: "Insights Engine",
      }}
      examples={[
        "AI-generated performance insights",
        "Automated optimization recommendations",
        "Risk detection and alerts",
        "Opportunity identification",
        "Anomaly detection",
        "Trend analysis",
        "Automated report generation",
      ]}
      stats={stats}
      actions={
        <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
          <CustomerSelector
            customers={customers}
            className="min-w-[180px] sm:min-w-[200px]"
          />
          <ViewScopeSelector />
        </div>
      }
    >
      {isLoading ? (
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-cyan-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-[#9ca3af]">Generating insights...</p>
          </div>
        </div>
      ) : (
        <AutomatedInsights
          insights={insights}
          reports={reports}
          onInsightAcknowledge={handleInsightAcknowledge}
          onReportGenerate={handleReportGenerate}
        />
      )}
    </PageTemplate>
  );
}
