/**
 * Legal Metadata Service
 *
 * Automatically tags evidence, events, and audit logs with legal metadata
 * Ensures proper classification of FACT vs INFERENCE vs DISPUTE
 * Tracks jurisdiction, applicable laws, and decision authority
 * Prevents legal conclusions and legal advice
 */

export type RecordType =
  | "FACT"
  | "INFERENCE"
  | "DISPUTE"
  | "OPINION"
  | "DECISION";

export type FactType =
  | "SYSTEM_GENERATED" // Generated by system automatically
  | "HUMAN_INPUT" // Entered by human user
  | "EXTERNAL_API" // Retrieved from external API
  | "SENSOR" // From IoT sensor or device
  | "CALCULATED"; // Calculated/derived value

export type VerificationLevel =
  | "VERIFIED" // Verified and confirmed
  | "UNVERIFIED" // Not yet verified
  | "DISPUTED" // Under dispute
  | "CONTRADICTED"; // Contradicted by other evidence

export interface DecisionAuthority {
  authority: string; // Who made the decision
  authorityType: "SYSTEM" | "HUMAN" | "AI" | "EXTERNAL";
  authorityRole?: string; // Role of decision maker
  overridden: boolean; // Was this decision overridden?
  overriddenBy?: string; // Who overrode it
  overriddenByRole?: string; // Role of person who overrode
  overrideReason?: string; // Reason for override
  overrideTimestamp?: Date | string;
  originalDecision?: any; // Original decision before override
}

export interface LegalMetadata {
  recordType: RecordType;
  factType?: FactType;
  verificationLevel?: VerificationLevel;
  jurisdiction?: string; // e.g., "Saudi Arabia", "UAE", "Global"
  applicableLaw?: string[]; // Which laws/regulations apply
  legalConclusion: boolean; // Is this a legal conclusion? (should be false)
  legalAdvice: boolean; // Is this legal advice? (should be false)
  systemOfRecord: boolean; // Is this the authoritative source?
  decisionAuthority?: DecisionAuthority;
}

class LegalMetadataService {
  /**
   * Detect record type from content and context
   */
  detectRecordType(content: any, context?: any): RecordType {
    // System-generated events are always FACT
    if (context?.source === "SYSTEM" || context?.automated === true) {
      return "FACT";
    }

    // Check content for inference indicators
    if (this.containsInferenceLanguage(content)) {
      return "INFERENCE";
    }

    // Check for dispute indicators
    if (this.containsDisputeLanguage(content)) {
      return "DISPUTE";
    }

    // Check for opinion indicators
    if (this.containsOpinionLanguage(content)) {
      return "OPINION";
    }

    // Default to FACT for system records
    return "FACT";
  }

  /**
   * Detect fact type based on source
   */
  detectFactType(source?: string, context?: any): FactType {
    if (!source && !context) return "SYSTEM_GENERATED";

    // Check source
    if (source === "SYSTEM" || source === "AUTOMATED") {
      return "SYSTEM_GENERATED";
    }
    if (source === "USER" || source === "HUMAN") {
      return "HUMAN_INPUT";
    }
    if (source === "API" || source === "EXTERNAL") {
      return "EXTERNAL_API";
    }
    if (source === "SENSOR" || source === "IOT" || source === "DEVICE") {
      return "SENSOR";
    }
    if (source === "CALCULATED" || source === "DERIVED") {
      return "CALCULATED";
    }

    // Check context
    if (context?.automated) return "SYSTEM_GENERATED";
    if (context?.userId) return "HUMAN_INPUT";
    if (context?.external) return "EXTERNAL_API";
    if (context?.deviceId) return "SENSOR";
    if (context?.calculation) return "CALCULATED";

    return "SYSTEM_GENERATED";
  }

  /**
   * Detect jurisdiction from context
   */
  detectJurisdiction(context?: any): string | undefined {
    if (!context) return undefined;

    // Check explicit jurisdiction
    if (context.jurisdiction) return context.jurisdiction;

    // Check location-based jurisdiction
    if (context.country) return context.country;
    if (context.location?.country) return context.location.country;

    // Check tenant-based jurisdiction
    if (context.tenantCountry) return context.tenantCountry;

    return undefined;
  }

  /**
   * Detect applicable laws
   */
  detectApplicableLaws(context?: any): string[] {
    const laws: string[] = [];

    if (!context) return laws;

    // Add explicit laws
    if (context.laws && Array.isArray(context.laws)) {
      laws.push(...context.laws);
    }

    // Add jurisdiction-based laws
    const jurisdiction = this.detectJurisdiction(context);
    if (jurisdiction) {
      // Add common laws for jurisdiction
      if (jurisdiction === "Saudi Arabia") {
        laws.push("Saudi Labor Law", "Saudi Commercial Law");
      }
      if (jurisdiction === "UAE") {
        laws.push("UAE Labor Law", "UAE Commercial Companies Law");
      }
    }

    // Add module-specific laws
    if (context.moduleId === "compliance") {
      laws.push("Regulatory Compliance Requirements");
    }
    if (context.moduleId === "trade-compliance") {
      laws.push("Customs Regulations", "Trade Compliance");
    }

    return [...new Set(laws)]; // Remove duplicates
  }

  /**
   * Detect if content contains legal conclusion
   */
  detectLegalConclusion(content: any): boolean {
    if (!content) return false;

    const text =
      typeof content === "string" ? content : JSON.stringify(content);
    const lowerText = text.toLowerCase();

    // Legal conclusion keywords
    const conclusionKeywords = [
      "liable for",
      "fault of",
      "responsible for breach",
      "negligent",
      "in violation of",
      "guilty of",
      "breach of duty",
      "legal liability",
      "legally responsible",
    ];

    return conclusionKeywords.some((keyword) => lowerText.includes(keyword));
  }

  /**
   * Detect if content contains legal advice
   */
  detectLegalAdvice(content: any): boolean {
    if (!content) return false;

    const text =
      typeof content === "string" ? content : JSON.stringify(content);
    const lowerText = text.toLowerCase();

    // Legal advice keywords
    const adviceKeywords = [
      "you should sue",
      "legal action recommended",
      "consult lawyer",
      "file lawsuit",
      "pursue litigation",
      "legal remedy",
      "take legal action",
    ];

    return adviceKeywords.some((keyword) => lowerText.includes(keyword));
  }

  /**
   * Generate complete legal metadata
   */
  generateLegalMetadata(
    content: any,
    context?: {
      source?: string;
      automated?: boolean;
      userId?: string;
      external?: boolean;
      deviceId?: string;
      calculation?: boolean;
      jurisdiction?: string;
      country?: string;
      location?: any;
      tenantCountry?: string;
      laws?: string[];
      moduleId?: string;
      authority?: string;
      authorityType?: "SYSTEM" | "HUMAN" | "AI" | "EXTERNAL";
      authorityRole?: string;
    },
  ): LegalMetadata {
    const recordType = this.detectRecordType(content, context);
    const factType = this.detectFactType(context?.source, context);
    const jurisdiction = this.detectJurisdiction(context);
    const applicableLaw = this.detectApplicableLaws(context);
    const legalConclusion = this.detectLegalConclusion(content);
    const legalAdvice = this.detectLegalAdvice(content);

    // System records are always system of record
    const systemOfRecord =
      recordType === "FACT" && factType === "SYSTEM_GENERATED";

    // Build decision authority if provided
    let decisionAuthority: DecisionAuthority | undefined;
    if (context?.authority) {
      decisionAuthority = {
        authority: context.authority,
        authorityType: context.authorityType || "SYSTEM",
        authorityRole: context.authorityRole,
        overridden: false,
      };
    }

    return {
      recordType,
      factType,
      verificationLevel: "UNVERIFIED", // Default, can be updated later
      jurisdiction,
      applicableLaw,
      legalConclusion,
      legalAdvice,
      systemOfRecord,
      decisionAuthority,
    };
  }

  /**
   * Validate legal metadata
   */
  validateLegalMetadata(metadata: LegalMetadata): {
    valid: boolean;
    errors: string[];
  } {
    const errors: string[] = [];

    // Legal conclusions should never be true
    if (metadata.legalConclusion) {
      errors.push(
        "Legal conclusion detected - system should not make legal conclusions",
      );
    }

    // Legal advice should never be true
    if (metadata.legalAdvice) {
      errors.push(
        "Legal advice detected - system should not provide legal advice",
      );
    }

    // System-generated facts should be system of record
    if (
      metadata.factType === "SYSTEM_GENERATED" &&
      metadata.recordType === "FACT" &&
      !metadata.systemOfRecord
    ) {
      errors.push("System-generated facts must be marked as system of record");
    }

    // Inferences should not be system of record
    if (metadata.recordType === "INFERENCE" && metadata.systemOfRecord) {
      errors.push("Inferences cannot be system of record");
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  /**
   * Check if content contains inference language
   */
  private containsInferenceLanguage(content: any): boolean {
    if (!content) return false;

    const text =
      typeof content === "string" ? content : JSON.stringify(content);
    const lowerText = text.toLowerCase();

    const inferenceKeywords = [
      "appears to",
      "seems to",
      "likely",
      "probably",
      "possibly",
      "may have",
      "could have",
      "suggests that",
      "indicates that",
      "implies that",
    ];

    return inferenceKeywords.some((keyword) => lowerText.includes(keyword));
  }

  /**
   * Check if content contains dispute language
   */
  private containsDisputeLanguage(content: any): boolean {
    if (!content) return false;

    const text =
      typeof content === "string" ? content : JSON.stringify(content);
    const lowerText = text.toLowerCase();

    const disputeKeywords = [
      "disputed",
      "contested",
      "disagreed",
      "challenged",
      "under dispute",
      "in dispute",
      "claim rejected",
      "claim denied",
    ];

    return disputeKeywords.some((keyword) => lowerText.includes(keyword));
  }

  /**
   * Check if content contains opinion language
   */
  private containsOpinionLanguage(content: any): boolean {
    if (!content) return false;

    const text =
      typeof content === "string" ? content : JSON.stringify(content);
    const lowerText = text.toLowerCase();

    const opinionKeywords = [
      "i think",
      "i believe",
      "in my opinion",
      "from my perspective",
      "i feel",
      "my view is",
      "personally",
    ];

    return opinionKeywords.some((keyword) => lowerText.includes(keyword));
  }
}

// ============================================================================
// EXPORT SINGLETON
// ============================================================================

export const legalMetadataService = new LegalMetadataService();
