/**
 * Knowledge Base Type Definitions
 * Self-learning architecture with isolated tenant/agent knowledge bases
 * Supports vector embeddings, RAG, and federated learning
 */

// ============================================================================
// CORE KNOWLEDGE TYPES
// ============================================================================

export interface KnowledgeEntry {
  id: string
  tenantId?: string // Optional for global knowledge
  agentId?: string // Optional for agent-specific knowledge
  type: KnowledgeType
  category: KnowledgeCategory | KnowledgeCategoryType
  
  // Content
  content: string
  summary?: string
  metadata: Record<string, any>
  
  // Embedding & Search
  embedding?: number[] // Vector embedding for semantic search
  keywords: string[]
  searchableText: string
  
  // Source & Lineage
  source: KnowledgeSource
  sourceId?: string // Reference to original document/event
  derivedFrom?: string[] // Parent knowledge IDs
  
  // Quality & Trust
  confidence: number // 0-100
  verified: boolean
  verifiedBy?: string
  verifiedAt?: Date | string
  feedbackScore: number // Aggregate of positive/negative feedback
  usageCount: number // How often this knowledge was retrieved
  
  // Lifecycle
  status: 'active' | 'archived' | 'deprecated' | 'pending_review'
  expiresAt?: Date | string
  createdAt: Date | string
  updatedAt: Date | string
  createdBy?: string
  version: number
}

export type KnowledgeType = 
  | 'fact' // Static factual information
  | 'rule' // Business rules and constraints
  | 'procedure' // Step-by-step procedures
  | 'pattern' // Learned patterns from data
  | 'insight' // AI-generated insights
  | 'solution' // Problem solutions
  | 'error_resolution' // Error fixes
  | 'best_practice' // Best practices
  | 'warning' // Warnings and caveats
  | 'relationship' // Entity relationships

export enum KnowledgeCategory {
  CHEMICAL_SAFETY = 'chemical_safety',
  STORAGE_COMPATIBILITY = 'storage_compatibility',
  COMPLIANCE = 'regulatory_compliance',
  WAREHOUSE_MANAGEMENT = 'warehouse_operations',
  TRANSPORTATION = 'transportation',
  QUALITY_MANAGEMENT = 'quality_management',
  RISK_MANAGEMENT = 'risk_assessment',
  ROOT_CAUSE_ANALYSIS = 'root_cause_analysis',
  PREDICTIVE_MAINTENANCE = 'predictive_maintenance',
  CUSTOMER_PREFERENCES = 'customer_preferences',
  SYSTEM_CONFIGURATION = 'system_configuration',
  ERROR_HANDLING = 'error_handling',
  GENERAL = 'general',
  SAFETY = 'safety',
  TRADE_COMPLIANCE = 'trade_compliance',
  TRAINING = 'training',
}

// Also export as type for backward compatibility
export type KnowledgeCategoryType = 
  | 'chemical_safety'
  | 'storage_compatibility'
  | 'regulatory_compliance'
  | 'warehouse_operations'
  | 'transportation'
  | 'quality_management'
  | 'risk_assessment'
  | 'root_cause_analysis'
  | 'predictive_maintenance'
  | 'customer_preferences'
  | 'system_configuration'
  | 'error_handling'
  | 'general'
  | 'safety'
  | 'trade_compliance'
  | 'training'

export type KnowledgeSource =
  | 'msds_parsing' // Extracted from MSDS documents
  | 'ai_analysis' // Generated by AI analysis
  | 'user_input' // Manually entered
  | 'feedback_learning' // Learned from user feedback
  | 'pattern_mining' // Discovered patterns
  | 'external_api' // From external sources
  | 'system_event' // From system events
  | 'historical_data' // From historical analysis
  | 'document_extraction' // From document processing
  | 'federated_learning' // Shared from other tenants (anonymized)

// ============================================================================
// EMBEDDING & SEARCH TYPES
// ============================================================================

export interface EmbeddingConfig {
  model: 'openai-ada-002' | 'openai-3-small' | 'openai-3-large' | 'local'
  dimensions: number
  maxTokens: number
}

export interface SearchQuery {
  query: string
  tenantId?: string
  agentId?: string
  filters?: {
    types?: KnowledgeType[]
    categories?: KnowledgeCategory[]
    sources?: KnowledgeSource[]
    minConfidence?: number
    verified?: boolean
    dateRange?: { start: Date; end: Date }
  }
  limit?: number
  threshold?: number // Minimum similarity score
  includeGlobal?: boolean // Include global knowledge
  includeFederated?: boolean // Include federated knowledge
}

export interface SearchResult {
  entry: KnowledgeEntry
  score: number // Similarity score 0-1
  highlights?: string[] // Relevant excerpts
  explanation?: string // Why this result matched
}

// ============================================================================
// TENANT KNOWLEDGE ISOLATION
// ============================================================================

export interface TenantKnowledgeConfig {
  tenantId: string
  
  // Knowledge Scope
  allowedCategories: (KnowledgeCategory | KnowledgeCategoryType)[]
  enabledSources: KnowledgeSource[]
  
  // Privacy & Sharing
  shareAnonymizedInsights: boolean // Contribute to federated learning
  receiveFederatedInsights: boolean // Receive shared insights
  dataRetentionDays: number
  
  // AI Settings
  enableAutoLearning: boolean
  learningThreshold: number // Min confidence for auto-learning
  reviewRequiredCategories: (KnowledgeCategory | KnowledgeCategoryType)[] // Require human review
  
  // Limits
  maxEntries: number
  maxStorageBytes: number
  
  // Status
  createdAt: Date | string
  updatedAt: Date | string
}

export interface AgentKnowledgeConfig {
  agentId: string
  agentType: string
  tenantId?: string // Optional, for tenant-specific agents
  
  // Knowledge Scope
  specializations: (KnowledgeCategory | KnowledgeCategoryType)[]
  accessibleCategories: (KnowledgeCategory | KnowledgeCategoryType)[]
  
  // Learning Settings
  enableContinuousLearning: boolean
  learningRate: number // How quickly to incorporate new knowledge
  forgetRate: number // How quickly to deprecate unused knowledge
  
  // Memory Settings
  shortTermMemorySize: number // Recent context window
  longTermMemorySize: number // Persistent knowledge count
  
  // Performance Tracking
  successfulRetrievals: number
  failedRetrievals: number
  feedbackScoreAvg: number
  
  createdAt: Date | string
  updatedAt: Date | string
}

// ============================================================================
// LEARNING & FEEDBACK TYPES
// ============================================================================

export interface LearningEvent {
  id: string
  type: LearningEventType
  tenantId?: string
  agentId?: string
  
  // Event Details
  trigger: string // What triggered the learning
  input: Record<string, any> // Input data
  output?: Record<string, any> // Output/result
  
  // Knowledge Impact
  createdKnowledge?: string[] // New knowledge IDs
  updatedKnowledge?: string[] // Updated knowledge IDs
  deprecatedKnowledge?: string[] // Deprecated knowledge IDs
  
  // Quality
  success: boolean
  confidence: number
  feedback?: Feedback
  
  timestamp: Date | string
  metadata: Record<string, any>
}

export type LearningEventType =
  | 'document_processed'
  | 'user_feedback'
  | 'pattern_discovered'
  | 'error_resolved'
  | 'prediction_validated'
  | 'rule_learned'
  | 'insight_generated'
  | 'federated_sync'

export interface Feedback {
  id: string
  knowledgeId: string
  userId?: string
  tenantId?: string
  
  type: 'positive' | 'negative' | 'correction'
  rating?: number // 1-5
  comment?: string
  
  // For corrections
  correctedContent?: string
  correctedMetadata?: Record<string, any>
  
  // Processing
  processed: boolean
  processedAt?: Date | string
  impactedLearning?: string[] // Learning event IDs
  
  createdAt: Date | string
}

// ============================================================================
// FEDERATED LEARNING TYPES
// ============================================================================

export interface FederatedInsight {
  id: string
  
  // Anonymized Content
  content: string
  summary: string
  category: KnowledgeCategory | KnowledgeCategoryType
  type: KnowledgeType
  
  // Aggregated Stats
  contributingTenants: number // Count, not IDs
  totalUsageCount: number
  averageConfidence: number
  averageFeedbackScore: number
  
  // Quality Control
  verified: boolean
  verifiedBy?: string // Admin or automated
  
  // Distribution
  availableTo: 'all' | 'premium' | 'specific_industries'
  industries?: string[]
  
  createdAt: Date | string
  updatedAt: Date | string
}

export interface FederationConfig {
  enabled: boolean
  
  // Contribution Settings
  contributeCategories: KnowledgeCategory[]
  minConfidenceToShare: number
  minUsageToShare: number
  
  // Reception Settings
  acceptCategories: KnowledgeCategory[]
  minFederatedConfidence: number
  
  // Privacy
  anonymizationLevel: 'full' | 'partial' | 'none'
  excludeFields: string[]
}

// ============================================================================
// SERVICE INTERFACES
// ============================================================================

export interface KnowledgeBaseService {
  // CRUD Operations
  create: (entry: Omit<KnowledgeEntry, 'id' | 'createdAt' | 'updatedAt' | 'version'>) => Promise<KnowledgeEntry>
  read: (id: string) => Promise<KnowledgeEntry | null>
  update: (id: string, updates: Partial<KnowledgeEntry>) => Promise<KnowledgeEntry>
  delete: (id: string) => Promise<boolean>
  archive: (id: string) => Promise<boolean>
  
  // Search
  search: (query: SearchQuery) => Promise<SearchResult[]>
  semanticSearch: (text: string, options?: Partial<SearchQuery>) => Promise<SearchResult[]>
  findSimilar: (knowledgeId: string, limit?: number) => Promise<SearchResult[]>
  
  // Embedding
  generateEmbedding: (text: string) => Promise<number[]>
  batchGenerateEmbeddings: (texts: string[]) => Promise<number[][]>
  
  // Learning
  learn: (event: Omit<LearningEvent, 'id' | 'timestamp'>) => Promise<LearningEvent>
  processFeedback: (feedback: Omit<Feedback, 'id' | 'createdAt' | 'processed'>) => Promise<Feedback>
  
  // Tenant Management
  getTenantConfig: (tenantId: string) => Promise<TenantKnowledgeConfig>
  updateTenantConfig: (tenantId: string, config: Partial<TenantKnowledgeConfig>) => Promise<TenantKnowledgeConfig>
  
  // Agent Management
  getAgentConfig: (agentId: string) => Promise<AgentKnowledgeConfig>
  updateAgentConfig: (agentId: string, config: Partial<AgentKnowledgeConfig>) => Promise<AgentKnowledgeConfig>
  
  // Federation
  syncFederatedInsights: () => Promise<FederatedInsight[]>
  contributeFederatedInsight: (knowledgeId: string) => Promise<boolean>
  
  // Statistics
  getStats: (tenantId?: string) => Promise<KnowledgeStats>
}

export interface KnowledgeStats {
  totalEntries: number
  entriesByType: Record<KnowledgeType, number>
  entriesByCategory: Record<KnowledgeCategory | KnowledgeCategoryType, number>
  entriesBySource: Record<KnowledgeSource, number>
  averageConfidence: number
  verifiedPercentage: number
  totalSearches: number
  totalLearningEvents: number
  feedbackStats: {
    positive: number
    negative: number
    corrections: number
  }
  storageUsedBytes: number
  lastSyncAt?: Date | string
}

// ============================================================================
// EXPORTS
// ============================================================================

export default KnowledgeEntry

