/**
 * Vision Learning Types
 * Types for self-learning vision system
 */

export interface DamagePattern {
  id: string
  patternId: string
  name: string
  description: string
  visualFeatures: {
    damageType: string[]
    location: string[]
    severity: string[]
    shape: string[]
    color: string[]
  }
  context: {
    area?: string
    equipment?: string[]
    material?: string[]
    carrier?: string[]
  }
  confidence: number
  occurrenceCount: number
  accuracy: number
  lastSeen: Date | string
  firstSeen: Date | string
  autoGeneratedRules: string[]
  preventionSuggestions: string[]
  tags: string[]
  tenantId?: string
  createdAt: Date | string
  updatedAt: Date | string
}

export interface LearningFeedback {
  id: string
  patternId: string
  photoId: string
  damageRecordId: string
  userCorrection?: {
    originalPrediction: string
    correctedValue: string
    field: string
  }
  validated: boolean
  validatedBy?: string
  validatedAt?: Date | string
  learningImpact: {
    patternConfidenceChange: number
    ruleUpdates: string[]
    knowledgeBaseUpdates: string[]
  }
  createdAt: Date | string
}

export interface PatternMatch {
  pattern: DamagePattern
  matchScore: number
  matchedFeatures: string[]
  confidence: number
  suggestedAction: string
}








