/**
 * Helper to serialize TransportJob to database parameters
 */

import { TransportJob } from "@/types/tms/transportJob";

export function serializeJobToParams(
  job: TransportJob,
  tenantId: string,
): any[] {
  return [
    job.id,
    job.recordId || null,
    job.jobName || null,
    job.jobNumber || null,
    job.jobType || null,
    job.jobStatus || null,
    job.jobOwnerId || null,
    job.jobOwner || null,
    job.createdById || null,
    job.createdBy || null,
    job.modifiedById || null,
    job.modifiedBy || null,
    job.createdTime || new Date(),
    job.modifiedTime || new Date(),
    job.lastActivityTime || new Date(),
    job.currency || "SAR",
    job.exchangeRate || null,
    job.customerId || null,
    job.customer || null,
    job.transporterId || null,
    job.transporter || null,
    job.containerNumber || null,
    job.shipmentNumber || null,
    job.shipmentType || null,
    job.shipmentTypeOther || null,
    job.shipmentOrigin || null,
    job.shipmentDestination || null,
    job.shipmentFinalDestination || null,
    job.shipmentWeight || null,
    job.numberOfContainersOnMBL || null,
    job.bookingNumber || null,
    job.masterBillOfLading || null,
    job.houseBillOfLading || null,
    job.orderNumber || null,
    job.poNumber || null,
    job.flexInvoiceNumber || null,
    job.refNo || null,
    job.transporterBill || null,
    job.bayanStatus || null,
    job.bayanNumber || null,
    job.bayanNumberEntry || null,
    job.bayanNumberExit || null,
    job.doStatus || null,
    job.manifestStatus || null,
    job.siStatus || null,
    job.truckType || null,
    job.vehiclePlateNumber || null,
    job.typeOfEquipment || null,
    job.oldContainer || null,
    job.driverId || null,
    job.driverName || null,
    job.driverMobileNumber || null,
    job.driverForeignMobileNumber || null,
    job.driverIqamaNumber || null,
    job.driverLicenseNumber || null,
    job.driverPassportNumber || null,
    job.driverNationality || null,
    job.polCountry || null,
    job.polLocation || null,
    job.podCountry || null,
    job.podLocation || null,
    job.polDetails || null,
    job.podDetails || null,
    job.dropOffPort || null,
    job.emptyContainerCollectionDepot || null,
    job.collectionPort || null,
    job.fullContainerDropOffDepot || null,
    job.storageTerminalName || null,
    job.foreignConsignee || null,
    job.localConsignee || null,
    job.consigneeName || null,
    job.consigneePhone || null,
    job.requestDate || null,
    job.loadingDate || null,
    job.loadingDateForWayBill || null,
    job.departureTimeForWayBill || null,
    job.dateOffload || null,
    job.saudiBorderArrival || null,
    job.saudiBorderDeparture || null,
    job.destinationBorderArrival || null,
    job.destinationBorderDeparture || null,
    job.transitBorderArrival || null,
    job.transitBorderDeparture || null,
    job.borderEntryNo || null,
    job.shipperArrival || null,
    job.shipperDeparture || null,
    job.consigneeArrival || null,
    job.consigneeDeparture || null,
    job.storageTerminalDateIn || null,
    job.storageTerminalDateOut || null,
    job.agreedRate || null,
    job.costTRP || null,
    job.otherExpenses || null,
    job.othersAmount || null,
    job.bridgeClearanceFees || null,
    job.ccBOEntry || null,
    job.ccBOExit || null,
    job.overWeight || null,
    job.totalCost || null,
    job.detentionLoadingDays || null,
    job.totalLoadingTime || null,
    job.totalOffloadingTime || null,
    job.transitTime || null,
    job.transitTime2 || null,
    job.laneId || null,
    job.laneName || null,
    job.dealId || null,
    job.deal || null,
    job.roundTrip || null,
    job.bankName || null,
    job.ibanNumber || null,
    job.containerReleaseOrderNumber || null,
    job.dispatcherName || null,
    job.notesAndInstructions || null,
    job.podDetails || null,
    job.eta || null,
    job.etaNotProvided || null,
    job.tag || null,
    job.locked || null,
    job.connectedToModule || null,
    job.connectedToId || null,
    job.tgaVerified || null,
    job.daleeliVerified || null,
    job.bayanSynced || null,
    tenantId,
    job.metadata ? JSON.stringify(job.metadata) : null,
  ];
}
