"use client";

import React, { useState } from "react";
import { brandMessagingService } from "@/lib/services/brand-messaging/brandMessagingService";
import type { MessagingGenerationRequest } from "@/types/brand-messaging";

export default function BrandMessagingTestPage() {
  const [testResults, setTestResults] = useState<string[]>([]);
  const [isRunning, setIsRunning] = useState(false);

  const runTests = async () => {
    setIsRunning(true);
    const results: string[] = [];

    try {
      // Test 1: Service Initialization
      results.push("🧪 Test 1: Service Initialization...");
      const stats = brandMessagingService.getCacheStats();
      if (stats) {
        results.push("✅ Service initialized successfully");
        results.push(`   Cache: ${stats.size}/${stats.maxSize} messages`);
      } else {
        results.push("❌ Service initialization failed");
      }

      // Test 2: Template Generation
      results.push("\n🧪 Test 2: Template Message Generation...");
      const request: MessagingGenerationRequest = {
        type: "module_header",
        context: {
          moduleId: "wms",
          moduleName: "Warehouse Management",
          language: "both",
        },
        useCache: false,
        qualityCheck: false,
        promptConfig: {
          systemPromptOverride: "template",
        },
      };

      const message = await brandMessagingService.generateMessage(request);
      if (message && message.content.en && message.content.ar) {
        results.push("✅ Message generated successfully");
        results.push(`   English: ${message.content.en}`);
        results.push(`   Arabic: ${message.content.ar}`);
        results.push(`   Generated by: ${message.metadata?.generatedBy}`);
      } else {
        results.push("❌ Message generation failed");
      }

      // Test 3: Quality Check
      results.push("\n🧪 Test 3: Quality Checking...");
      const qualityRequest: MessagingGenerationRequest = {
        ...request,
        qualityCheck: true,
      };
      const qualityMessage =
        await brandMessagingService.generateMessage(qualityRequest);
      if (qualityMessage.metadata?.qualityScore !== undefined) {
        results.push(
          `✅ Quality check completed: ${qualityMessage.metadata.qualityScore}%`,
        );
      } else {
        results.push("❌ Quality check failed");
      }

      // Test 4: Cache
      results.push("\n🧪 Test 4: Caching...");
      const cached1 = await brandMessagingService.generateMessage({
        ...request,
        useCache: true,
      });
      const cached2 = await brandMessagingService.generateMessage({
        ...request,
        useCache: true,
      });
      if (cached1.id === cached2.id) {
        results.push("✅ Cache working correctly");
      } else {
        results.push("❌ Cache not working");
      }

      // Test 5: Batch Generation
      results.push("\n🧪 Test 5: Batch Generation...");
      const batchResult = await brandMessagingService.batchGenerate({
        items: [
          {
            type: "module_header",
            context: { moduleId: "wms", moduleName: "WMS", language: "both" },
          },
          {
            type: "empty_state",
            context: { moduleId: "wms", language: "both" },
          },
        ],
        parallel: false,
      });
      if (batchResult.messages.length === 2) {
        results.push(
          `✅ Batch generation successful: ${batchResult.messages.length} messages`,
        );
        results.push(`   Time: ${batchResult.generationTime}ms`);
      } else {
        results.push("❌ Batch generation failed");
      }

      // Test 6: API Endpoint
      results.push("\n🧪 Test 6: API Endpoint...");
      try {
        const apiResponse = await fetch("/api/brand-messaging/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(request),
        });
        const apiData = await apiResponse.json();
        if (apiData.success && apiData.data) {
          results.push("✅ API endpoint working");
        } else {
          results.push("❌ API endpoint failed");
        }
      } catch (error) {
        results.push(`❌ API endpoint error: ${error}`);
      }

      results.push("\n✅ All tests completed!");
    } catch (error) {
      results.push(`\n❌ Test error: ${error}`);
    } finally {
      setIsRunning(false);
      setTestResults(results);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="bg-slate-800/50 rounded-xl p-6 border border-slate-700">
          <h1 className="text-3xl font-bold mb-4 bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
            Brand Messaging Engine - Test Suite
          </h1>
          <p className="text-slate-400 mb-6">
            Run automated tests to verify the Brand Messaging Engine is working
            correctly
          </p>

          <button
            onClick={runTests}
            disabled={isRunning}
            className="bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white font-semibold py-3 px-6 rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed mb-6"
          >
            {isRunning ? "Running Tests..." : "🚀 Run Tests"}
          </button>

          {testResults.length > 0 && (
            <div className="bg-slate-900 rounded-lg p-6 border border-slate-600">
              <h2 className="text-xl font-semibold mb-4">Test Results</h2>
              <pre className="text-sm font-mono whitespace-pre-wrap text-green-400">
                {testResults.join("\n")}
              </pre>
            </div>
          )}

          <div className="mt-6 p-4 bg-blue-500/20 border border-blue-500/50 rounded-lg">
            <p className="text-sm text-blue-300">
              <strong>Note:</strong> These tests verify core functionality. For
              full testing, use the main dashboard at{" "}
              <a
                href="/brand-messaging"
                className="underline hover:text-blue-200"
              >
                /brand-messaging
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
