/**
 * Customs Declaration Lifecycle Configuration
 *
 * Note: lifecycle storage is currently in-memory and keyed by `${entityType}:${entityId}`.
 * For tenant isolation, call sites should use composite entityId: `${tenantId}::${declarationId}`.
 */

import type { LifecycleConfig } from "@/types/lifecycle";

export const customsDeclarationLifecycleConfig: LifecycleConfig = {
  entityType: "CUSTOMS_DECLARATION",
  name: "Customs Declaration Lifecycle",
  description:
    "Customs declaration processing from creation → documents → submission → clearance → evidence packet",
  version: "1.0.0",
  stages: [
    {
      id: "CUSTOMS_DECLARATION_CREATED",
      code: "CREATED",
      name: "Created",
      description: "Declaration created and awaiting documents",
      icon: "ri-file-add-line",
      color: "#60a5fa",
      order: 1,
      isRequired: true,
      isOptional: false,
      canSkip: false,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "tms",
          action: "view_customs",
          label: "Open Customs",
          href: "/transportation/customs",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_DOCS_REQUIRED",
      code: "DOCS_REQUIRED",
      name: "Docs Required",
      description: "Required documents identified and requested/expected",
      icon: "ri-file-list-3-line",
      color: "#f59e0b",
      order: 2,
      isRequired: true,
      isOptional: false,
      canSkip: true,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "tms",
          action: "attach_documents",
          label: "Attach Documents",
          href: "/transportation/customs",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_DOCS_ATTACHED",
      code: "DOCS_ATTACHED",
      name: "Docs Attached",
      description: "Documents attached and ready for submission",
      icon: "ri-attachment-2",
      color: "#22c55e",
      order: 3,
      isRequired: true,
      isOptional: false,
      canSkip: false,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "tms",
          action: "submit_customs",
          label: "Submit Declaration",
          href: "/transportation/customs",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_SUBMISSION_REQUESTED",
      code: "SUBMISSION_REQUESTED",
      name: "Submission Requested",
      description:
        "Submission queued (integration-first) for adapter processing",
      icon: "ri-send-plane-2-line",
      color: "#a78bfa",
      order: 4,
      isRequired: true,
      isOptional: false,
      canSkip: false,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "integration",
          action: "monitor",
          label: "Integration Monitor",
          href: "/integration",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_SUBMITTED",
      code: "SUBMITTED",
      name: "Submitted",
      description:
        "Submitted to external system (or mock adapter) and under review",
      icon: "ri-timer-flash-line",
      color: "#38bdf8",
      order: 5,
      isRequired: true,
      isOptional: false,
      canSkip: false,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "tms",
          action: "track_customs",
          label: "Track Status",
          href: "/transportation/customs",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_CLEARED",
      code: "CLEARED",
      name: "Cleared",
      description: "Cleared/approved by customs",
      icon: "ri-shield-check-line",
      color: "#10b981",
      order: 6,
      isRequired: false,
      isOptional: true,
      canSkip: true,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "tms",
          action: "view_customs",
          label: "Open Customs",
          href: "/transportation/customs",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_REJECTED",
      code: "REJECTED",
      name: "Rejected",
      description: "Rejected by customs; requires correction and resubmission",
      icon: "ri-forbid-2-line",
      color: "#ef4444",
      order: 7,
      isRequired: false,
      isOptional: true,
      canSkip: true,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "tms",
          action: "fix_customs",
          label: "Fix & Resubmit",
          href: "/transportation/customs",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_FAILED",
      code: "FAILED",
      name: "Failed",
      description:
        "Submission failed (integration error, validation error, system outage)",
      icon: "ri-error-warning-line",
      color: "#f97316",
      order: 8,
      isRequired: false,
      isOptional: true,
      canSkip: true,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "integration",
          action: "debug",
          label: "Debug Integration",
          href: "/integration",
        },
      ],
      actions: [],
    },
    {
      id: "CUSTOMS_EVIDENCE_PACKET",
      code: "EVIDENCE_PACKET",
      name: "Evidence Packet",
      description: "Court-ready evidence packet generated for the declaration",
      icon: "ri-file-shield-2-line",
      color: "#22c55e",
      order: 9,
      isRequired: false,
      isOptional: true,
      canSkip: true,
      estimatedDuration: 0,
      slaTarget: 0,
      requiresApproval: false,
      approvalRoles: [],
      autoTransition: { enabled: false },
      conditions: [],
      moduleLinks: [
        {
          module: "reports",
          action: "view_evidence",
          label: "View Evidence",
          href: "/reports",
        },
      ],
      actions: [],
    },
  ],
};
