"use client";

import { useState, useEffect } from "react";
import PageTemplate from "@/components/PageTemplate";
import { eventStore } from "@/lib/services/event-store";

export default function EventStorePage() {
  const [events, setEvents] = useState<any[]>([]);
  const [position, setPosition] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadEvents();
  }, []);

  const loadEvents = async () => {
    setLoading(true);
    try {
      const allEvents = await eventStore.getAllEvents(0, 100);
      setEvents(allEvents);
      const pos = await eventStore.getPosition();
      setPosition(pos);
    } catch (error) {
      console.error("Error loading events:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageTemplate
      title="Event Store"
      description="Event Sourcing & CQRS - Append-Only Event Log"
      icon="ri-database-line"
      stats={[
        {
          label: "Total Events",
          value: position,
          icon: "ri-database-line",
          trend: "up" as const,
        },
        {
          label: "Loaded Events",
          value: events.length,
          icon: "ri-file-list-line",
          trend: "neutral" as const,
        },
      ]}
    >
      <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6">
        {loading ? (
          <div className="text-center py-12 text-[#9ca3af]">
            Loading events...
          </div>
        ) : events.length === 0 ? (
          <div className="text-center py-12 text-[#9ca3af]">
            <i className="ri-database-line text-4xl mb-3 opacity-50"></i>
            <p>No events in store</p>
            <p className="text-sm mt-2">
              Events will appear here as they are generated by the system
            </p>
          </div>
        ) : (
          <div className="space-y-2 max-h-[600px] overflow-y-auto">
            {events.map((event) => (
              <div
                key={event.id}
                className="bg-white/5 border border-white/10 rounded-lg p-3"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-white font-medium">{event.type}</span>
                    <span className="text-xs text-[#9ca3af] ml-2">
                      {event.aggregateType}
                    </span>
                    <span className="text-xs text-[#6b7280] ml-2">
                      v{event.version}
                    </span>
                  </div>
                  <span className="text-xs text-[#6b7280]">
                    {new Date(event.timestamp).toLocaleString()}
                  </span>
                </div>
                {event.payload && (
                  <div className="mt-2 text-xs text-[#9ca3af] font-mono bg-black/20 p-2 rounded overflow-x-auto">
                    {JSON.stringify(event.payload, null, 2).substring(0, 200)}
                    {JSON.stringify(event.payload).length > 200 && "..."}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </PageTemplate>
  );
}
