"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  FiDollarSign,
  FiTrendingUp,
  FiClock,
  FiShield,
  FiUsers,
  FiZap,
  FiInfo,
  FiLayers,
} from "react-icons/fi";
import Tooltip from "@/components/Tooltip";

const CUSTOMER_PROFILES = [
  {
    name: "Custom",
    employees: 100,
    monthlyRevenue: 1000000,
    currentEfficiency: 75,
    currentCost: 50000,
    description: "Manual adjustment mode",
  },
  {
    name: "Global Retailer",
    employees: 5000,
    monthlyRevenue: 8500000,
    currentEfficiency: 65,
    currentCost: 250000,
    description: "Complex multi-channel retail operations",
  },
  {
    name: "Mid-Market Mfg",
    employees: 450,
    monthlyRevenue: 2500000,
    currentEfficiency: 55,
    currentCost: 75000,
    description: "Regional manufacturing & distribution",
  },
  {
    name: "Large 3PL Provider",
    employees: 1200,
    monthlyRevenue: 4000000,
    currentEfficiency: 80,
    currentCost: 120000,
    description: "Third-party logistics with high volume",
  },
];

interface ValueCalculatorProps {
  initialPersona?: string;
}

export default function ValueCalculator({
  initialPersona,
}: ValueCalculatorProps) {
  const [selectedProfile, setSelectedProfile] = useState(CUSTOMER_PROFILES[0]);
  const [inputs, setInputs] = useState({
    employees: 100,
    monthlyRevenue: 1000000,
    currentEfficiency: 75,
    currentCost: 50000,
  });

  // Update profile when initialPersona changes
  useEffect(() => {
    if (initialPersona) {
      const profileMap: Record<string, string> = {
        Retail: "Global Retailer",
        Logistics: "Large 3PL Provider",
        Manufacturing: "Mid-Market Mfg",
        Generic: "Custom",
      };
      const profileName = profileMap[initialPersona];
      if (profileName) {
        const profile = CUSTOMER_PROFILES.find((p) => p.name === profileName);
        if (profile) {
          setInputs({
            employees: profile.employees,
            monthlyRevenue: profile.monthlyRevenue,
            currentEfficiency: profile.currentEfficiency,
            currentCost: profile.currentCost,
          });
          setSelectedProfile(profile);
        }
      }
    }
  }, [initialPersona]);

  const handleProfileChange = (profileName: string) => {
    const profile =
      CUSTOMER_PROFILES.find((p) => p.name === profileName) ||
      CUSTOMER_PROFILES[0];
    setSelectedProfile(profile);
    setInputs({
      employees: profile.employees,
      monthlyRevenue: profile.monthlyRevenue,
      currentEfficiency: profile.currentEfficiency,
      currentCost: profile.currentCost,
    });
  };

  const calculateROI = () => {
    const efficiencyGain = (100 - inputs.currentEfficiency) * 0.3;
    const newEfficiency = inputs.currentEfficiency + efficiencyGain;
    const revenueIncrease = inputs.monthlyRevenue * (efficiencyGain / 100);
    const costReduction = inputs.currentCost * 0.25;
    const timeSavings = inputs.employees * 10;
    const totalMonthlyValue =
      revenueIncrease + costReduction + timeSavings * 50;
    const annualValue = totalMonthlyValue * 12;
    const roi =
      ((annualValue - inputs.currentCost * 12) / (inputs.currentCost * 12)) *
      100;

    return {
      efficiencyGain,
      newEfficiency,
      revenueIncrease,
      costReduction,
      timeSavings,
      totalMonthlyValue,
      annualValue,
      roi,
    };
  };

  const results = calculateROI();

  const inputFields = [
    {
      label: "Number of Employees",
      key: "employees",
      icon: FiUsers,
      min: 10,
      max: 10000,
      step: 10,
      format: (v: number) => v.toLocaleString(),
      tooltip: {
        content:
          "The total number of full-time employees involved in your supply chain and logistics operations.",
        examples: [
          "Logistics coordinators and warehouse staff",
          "IT teams managing legacy software systems",
          "Management overseeing operational workflows",
        ],
      },
    },
    {
      label: "Monthly Revenue (USD)",
      key: "monthlyRevenue",
      icon: FiDollarSign,
      min: 10000,
      max: 10000000,
      step: 10000,
      format: (v: number) => `$${v.toLocaleString()}`,
      tooltip: {
        content:
          "Average gross revenue generated by your organization per month.",
        examples: [
          "Direct sales through retail or e-commerce",
          "Distribution and wholesale contracts",
          "Service-based logistics revenue",
        ],
      },
    },
    {
      label: "Current Efficiency (%)",
      key: "currentEfficiency",
      icon: FiTrendingUp,
      min: 50,
      max: 95,
      step: 5,
      format: (v: number) => `${v}%`,
      tooltip: {
        content:
          "How much of your operational capacity is effectively utilized without manual rework or errors.",
        examples: [
          "75%: 1 out of 4 orders needs manual intervention",
          "50%: Team spends half their day on manual data entry",
          "90%: High automation but multi-vendor delays",
        ],
        systemInfo: {
          sap: "Usually requires 15-20% manual work for complex integrations",
          oracle: "High efficiency in finance, lower in field logistics",
          custom: "BlueDXP targets 99%+ efficiency through AI orchestration",
        },
      },
    },
    {
      label: "Current Monthly IT Cost (USD)",
      key: "currentCost",
      icon: FiDollarSign,
      min: 5000,
      max: 500000,
      step: 5000,
      format: (v: number) => `$${v.toLocaleString()}`,
      tooltip: {
        content:
          "Total expenditure on maintaining current IT infrastructure and licenses.",
        examples: [
          "Monthly license and support fees (SAP/Oracle)",
          "On-premise server maintenance costs",
          "IT contractors for legacy system updates",
        ],
      },
    },
  ];

  return (
    <div className="space-y-8">
      {/* Customer Profile Selector */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="p-6 bg-slate-800/50 rounded-xl border border-slate-700/50 backdrop-blur-sm"
      >
        <div className="flex flex-col md:flex-row items-center gap-6">
          <div className="flex-1">
            <h4 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
              <FiLayers className="text-blue-400" />
              Select Industry Profile
            </h4>
            <p className="text-sm text-slate-400">
              Choose a profile to see intelligent numbers based on industry
              standards
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            {CUSTOMER_PROFILES.map((profile) => (
              <button
                key={profile.name}
                onClick={() => handleProfileChange(profile.name)}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                  selectedProfile.name === profile.name
                    ? "bg-blue-600 text-white shadow-lg shadow-blue-500/50"
                    : "bg-slate-700/50 text-slate-300 hover:bg-slate-700 hover:text-white"
                }`}
              >
                {profile.name}
              </button>
            ))}
          </div>
        </div>
      </motion.div>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Inputs */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          className="space-y-6 p-6 bg-slate-800/50 rounded-xl border border-slate-700"
        >
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-2xl font-bold text-white">
              Your Current Situation
            </h3>
            {selectedProfile.name !== "Custom" && (
              <span className="text-xs px-2 py-1 bg-blue-500/20 text-blue-400 rounded-full border border-blue-500/30">
                {selectedProfile.description}
              </span>
            )}
          </div>

          {inputFields.map((input) => (
            <div key={input.key} className="group">
              <div className="flex items-center justify-between mb-2">
                <label className="flex items-center gap-2 text-slate-300">
                  <input.icon className="w-5 h-5 text-blue-400" />
                  {input.label}
                </label>
                <Tooltip
                  content={input.tooltip.content}
                  examples={input.tooltip.examples}
                  systemInfo={
                    "systemInfo" in input.tooltip
                      ? (input.tooltip.systemInfo as any)
                      : undefined
                  }
                >
                  <FiInfo className="w-4 h-4 text-slate-500 hover:text-blue-400 cursor-help transition-colors" />
                </Tooltip>
              </div>
              <input
                type="range"
                min={input.min}
                max={input.max}
                step={input.step}
                value={inputs[input.key as keyof typeof inputs]}
                onChange={(e) => {
                  setInputs((prev) => ({
                    ...prev,
                    [input.key]: Number(e.target.value),
                  }));
                  setSelectedProfile(CUSTOMER_PROFILES[0]); // Switch to Custom on manual change
                }}
                className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-blue-500"
              />
              <div className="flex justify-between text-sm text-slate-400 mt-1">
                <span>{input.format(input.min)}</span>
                <span className="text-blue-400 font-semibold text-lg">
                  {input.format(inputs[input.key as keyof typeof inputs])}
                </span>
                <span>{input.format(input.max)}</span>
              </div>
            </div>
          ))}
        </motion.div>

        {/* Results */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          className="space-y-6"
        >
          <div className="p-6 bg-gradient-to-br from-blue-600/20 to-cyan-600/20 rounded-xl border border-blue-500/30">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-2xl font-bold text-white">Projected Value</h3>
              <Tooltip content="Calculations based on 4IR/5IR automation standards and documented BlueDXP performance metrics.">
                <FiInfo className="w-5 h-5 text-blue-400 cursor-help" />
              </Tooltip>
            </div>

            <div className="space-y-4">
              <motion.div
                initial={{ scale: 0.9 }}
                animate={{ scale: 1 }}
                className="p-4 bg-slate-800/50 rounded-lg group"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-slate-400">
                      Efficiency Improvement
                    </span>
                    <Tooltip content="Based on BlueDXP's automation of manual gaps found in legacy ERP workflows.">
                      <FiInfo className="w-4 h-4 text-slate-600 group-hover:text-green-400 transition-colors" />
                    </Tooltip>
                  </div>
                  <span className="text-2xl font-bold text-green-400">
                    +{results.efficiencyGain.toFixed(1)}%
                  </span>
                </div>
                <div className="text-sm text-slate-300">
                  From {inputs.currentEfficiency}% to{" "}
                  {results.newEfficiency.toFixed(1)}%
                </div>
              </motion.div>

              <motion.div
                initial={{ scale: 0.9 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.1 }}
                className="p-4 bg-slate-800/50 rounded-lg group"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-slate-400">
                      Monthly Revenue Increase
                    </span>
                    <Tooltip content="Result of faster order-to-cash cycles and reduced data entry bottlenecks.">
                      <FiInfo className="w-4 h-4 text-slate-600 group-hover:text-blue-400 transition-colors" />
                    </Tooltip>
                  </div>
                  <span className="text-2xl font-bold text-blue-400">
                    ${results.revenueIncrease.toLocaleString()}
                  </span>
                </div>
              </motion.div>

              <motion.div
                initial={{ scale: 0.9 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.2 }}
                className="p-4 bg-slate-800/50 rounded-lg group"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-slate-400">
                      Monthly Cost Reduction
                    </span>
                    <Tooltip content="Savings from server consolidation, license optimization, and reduced IT support needs.">
                      <FiInfo className="w-4 h-4 text-slate-600 group-hover:text-cyan-400 transition-colors" />
                    </Tooltip>
                  </div>
                  <span className="text-2xl font-bold text-cyan-400">
                    ${results.costReduction.toLocaleString()}
                  </span>
                </div>
              </motion.div>

              <motion.div
                initial={{ scale: 0.9 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.3 }}
                className="p-4 bg-slate-800/50 rounded-lg group"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-slate-400">Time Savings</span>
                    <Tooltip content="Estimated 10 hours saved per employee per month through AI-driven task orchestration.">
                      <FiInfo className="w-4 h-4 text-slate-600 group-hover:text-purple-400 transition-colors" />
                    </Tooltip>
                  </div>
                  <span className="text-2xl font-bold text-purple-400">
                    {results.timeSavings.toLocaleString()} hrs/month
                  </span>
                </div>
              </motion.div>

              <motion.div
                initial={{ scale: 0.9 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.4 }}
                className="p-6 bg-gradient-to-r from-blue-600 to-cyan-600 rounded-lg mt-6"
              >
                <div className="text-slate-200 mb-2">Total Annual Value</div>
                <motion.div
                  key={results.annualValue}
                  initial={{ scale: 1.2 }}
                  animate={{ scale: 1 }}
                  className="text-4xl font-bold text-white mb-2"
                >
                  ${results.annualValue.toLocaleString()}
                </motion.div>
                <div className="text-blue-100">
                  ROI:{" "}
                  <span className="font-bold text-white">
                    {results.roi.toFixed(0)}%
                  </span>
                </div>
              </motion.div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
