/**
 * BIM Marketplace Mock Data
 * Comprehensive sample data for marketplace listings, providers, and reviews
 */

import type {
  BIMMarketplaceListing,
  BIMProvider,
} from "@/types/bim-marketplace";

export const mockBIMProviders: BIMProvider[] = [
  {
    id: "bim-provider-1",
    type: "company",
    name: "BIM Solutions Inc.",
    displayName: "BIM Solutions Inc.",
    description:
      "Leading BIM consulting and modeling services with 15+ years of experience. Specialized in large-scale commercial and industrial projects.",
    logo: "/logos/bim-solutions.png",
    email: "contact@bimsolutions.com",
    website: "https://bimsolutions.com",
    location: {
      country: "USA",
      region: "California",
      city: "San Francisco",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    verified: true,
    verifiedAt: new Date("2024-01-15"),
    verificationBadges: ["VERIFIED", "PREMIUM"],
    averageRating: 4.8,
    totalReviews: 127,
    totalListings: 45,
    specializations: ["architectural", "structural", "mep", "fire-safety"],
    certifications: ["Autodesk Certified", "BIM Level 2", "ISO 19650"],
    memberships: ["AIA", "BIM Forum", "BuildingSMART"],
    portfolio: ["/portfolio/project1.jpg", "/portfolio/project2.jpg"],
    status: "active",
    metadata: {
      established: 2008,
      employees: 150,
      projectsCompleted: 500,
    },
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "bim-provider-2",
    type: "company",
    name: "Digital Construction Group",
    displayName: "Digital Construction Group",
    description:
      "Innovative BIM and digital twin solutions for smart buildings and infrastructure.",
    logo: "/logos/digital-construction.png",
    email: "info@digitalconstruction.com",
    website: "https://digitalconstruction.com",
    location: {
      country: "UK",
      region: "England",
      city: "London",
      coordinates: { lat: 51.5074, lng: -0.1278 },
    },
    verified: true,
    verifiedAt: new Date("2024-02-20"),
    verificationBadges: ["VERIFIED"],
    averageRating: 4.9,
    totalReviews: 89,
    totalListings: 32,
    specializations: ["digital-twin", "facility-management", "sustainability"],
    certifications: ["BIM Level 3", "ISO 19650", "LEED Certified"],
    memberships: ["RIBA", "BuildingSMART"],
    portfolio: ["/portfolio/digital-twin1.jpg"],
    status: "active",
    metadata: {
      established: 2015,
      employees: 80,
      projectsCompleted: 200,
    },
    createdAt: new Date("2023-07-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "bim-provider-3",
    type: "individual",
    name: "John Smith",
    displayName: "John Smith, BIM Specialist",
    description:
      "Senior BIM Coordinator with expertise in MEP coordination and clash detection. Available for consulting and project management.",
    logo: "/avatars/john-smith.jpg",
    email: "john.smith@bimconsulting.com",
    website: "https://johnsmith-bim.com",
    location: {
      country: "USA",
      region: "New York",
      city: "New York",
      coordinates: { lat: 40.7128, lng: -74.006 },
    },
    verified: true,
    verifiedAt: new Date("2024-03-10"),
    verificationBadges: ["VERIFIED"],
    averageRating: 4.7,
    totalReviews: 45,
    totalListings: 12,
    specializations: ["mep", "coordination", "consulting"],
    certifications: ["Autodesk Certified Professional", "PMP"],
    memberships: ["AIA", "ASPE"],
    portfolio: [],
    status: "active",
    metadata: {
      experience: 12,
      education: ["M.S. Civil Engineering", "B.S. Architecture"],
    },
    createdAt: new Date("2023-08-01"),
    updatedAt: new Date("2024-12-01"),
  },
];

export const mockBIMMarketplaceListings: BIMMarketplaceListing[] = [
  {
    id: "listing-1",
    type: "model",
    title: "Modern Office Building - Complete BIM Model",
    description:
      "Comprehensive BIM model of a 10-story office building with full architectural, structural, and MEP systems. LOD 400, ready for construction. Includes detailed families, schedules, and documentation.",
    category: "architectural",
    subcategory: "commercial",
    providerId: "bim-provider-1",
    providerName: "BIM Solutions Inc.",
    providerRating: 4.8,
    providerVerified: true,
    pricing: {
      model: "one-time",
      amount: 299.99,
      currency: "USD",
      trialAvailable: true,
      trialDays: 7,
    },
    modelData: {
      fileFormat: "ifc",
      fileSize: 52428800,
      fileUrl: "/bim/models/office-building.ifc",
      previewUrl: "/bim/previews/office-building-preview.jpg",
      thumbnailUrl: "/bim/thumbnails/office-building-thumb.jpg",
      lod: "LOD 400",
      systems: ["architectural", "structural", "mep"],
      elements: 12500,
      area: 15000,
      volume: 180000,
      floors: 10,
      buildingType: "Office",
      projectType: "Commercial",
      year: 2024,
      software: "Revit 2024",
      version: "2024.1",
      license: "royalty-free",
      licenseTerms: "Commercial use allowed. Modification permitted.",
    },
    tags: [
      "office",
      "commercial",
      "modern",
      "sustainable",
      "leed",
      "high-rise",
    ],
    images: [
      "/bim/previews/office-1.jpg",
      "/bim/previews/office-2.jpg",
      "/bim/previews/office-3.jpg",
    ],
    videos: ["/bim/videos/office-tour.mp4"],
    documentation: [
      "/bim/docs/office-specs.pdf",
      "/bim/docs/office-manual.pdf",
    ],
    reviews: [
      {
        id: "review-1",
        listingId: "listing-1",
        userId: "user-1",
        userName: "Sarah Johnson",
        userAvatar: "/avatars/sarah.jpg",
        rating: 5,
        title: "Excellent quality model",
        comment: "Very detailed and well-organized. Saved us weeks of work!",
        verified: true,
        helpful: 12,
        createdAt: new Date("2024-11-15"),
        updatedAt: new Date("2024-11-15"),
      },
      {
        id: "review-2",
        listingId: "listing-1",
        userId: "user-2",
        userName: "Michael Chen",
        rating: 4,
        title: "Good value",
        comment:
          "Good model, minor issues with some families but overall satisfied.",
        verified: true,
        helpful: 5,
        createdAt: new Date("2024-11-20"),
        updatedAt: new Date("2024-11-20"),
      },
    ],
    averageRating: 4.7,
    reviewCount: 23,
    downloadCount: 156,
    viewCount: 892,
    favoriteCount: 45,
    status: "published",
    featured: true,
    verified: true,
    location: {
      country: "USA",
      region: "California",
      city: "San Francisco",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    availability: "available",
    compatibleSoftware: [
      "Revit",
      "Navisworks",
      "BIM 360",
      "Autodesk Construction Cloud",
    ],
    compatibleFormats: ["ifc", "rvt", "nwd"],
    metadata: {
      projectName: "Tech Park Office Complex",
      client: "Confidential",
      completionDate: "2024-12-01",
    },
    tenantId: "tenant-1",
    createdAt: new Date("2024-10-15"),
    updatedAt: new Date("2024-12-01"),
    publishedAt: new Date("2024-10-16"),
  },
  {
    id: "listing-2",
    type: "model",
    title: "Warehouse Facility - Structural BIM Model",
    description:
      "Complete structural BIM model for a 50,000 sq ft warehouse facility. Includes foundation, steel frame, and precast elements. LOD 350.",
    category: "structural",
    subcategory: "industrial",
    providerId: "bim-provider-1",
    providerName: "BIM Solutions Inc.",
    providerRating: 4.8,
    providerVerified: true,
    pricing: {
      model: "one-time",
      amount: 199.99,
      currency: "USD",
    },
    modelData: {
      fileFormat: "rvt",
      fileSize: 31457280,
      fileUrl: "/bim/models/warehouse-structural.rvt",
      previewUrl: "/bim/previews/warehouse-preview.jpg",
      lod: "LOD 350",
      systems: ["structural"],
      elements: 8500,
      area: 50000,
      volume: 500000,
      floors: 1,
      buildingType: "Warehouse",
      projectType: "Industrial",
      year: 2024,
      software: "Revit 2024",
      version: "2024.1",
      license: "single-use",
      licenseTerms: "Single project use only.",
    },
    tags: ["warehouse", "structural", "industrial", "steel-frame", "precast"],
    images: ["/bim/previews/warehouse-1.jpg", "/bim/previews/warehouse-2.jpg"],
    reviews: [],
    averageRating: 4.5,
    reviewCount: 8,
    downloadCount: 42,
    viewCount: 234,
    favoriteCount: 12,
    status: "published",
    featured: false,
    verified: true,
    location: {
      country: "USA",
      region: "Texas",
      city: "Houston",
    },
    availability: "available",
    compatibleSoftware: ["Revit", "Navisworks"],
    compatibleFormats: ["rvt", "ifc"],
    metadata: {},
    tenantId: "tenant-1",
    createdAt: new Date("2024-09-20"),
    updatedAt: new Date("2024-11-15"),
    publishedAt: new Date("2024-09-21"),
  },
  {
    id: "listing-3",
    type: "service",
    title: "BIM Coordination Services",
    description:
      "Professional BIM coordination services including clash detection, model integration, and coordination meetings. Experienced team with 10+ years in MEP coordination.",
    category: "consulting",
    subcategory: "coordination",
    providerId: "bim-provider-3",
    providerName: "John Smith, BIM Specialist",
    providerRating: 4.7,
    providerVerified: true,
    pricing: {
      model: "usage-based",
      usageUnit: "hour",
      usagePrice: 150,
      currency: "USD",
      customQuote: true,
    },
    serviceData: {
      serviceType: "coordination",
      deliverables: [
        "Clash detection reports",
        "Coordination models",
        "Meeting minutes",
        "Resolution recommendations",
      ],
      duration: "2-4 weeks",
      expertise: [
        "MEP Coordination",
        "Clash Detection",
        "Model Integration",
        "Navisworks",
      ],
      certifications: ["Autodesk Certified Professional"],
      portfolio: ["/portfolio/coordination-project1.jpg"],
      availability: "scheduled",
      responseTime: "24 hours",
      languages: ["English"],
    },
    tags: [
      "coordination",
      "clash-detection",
      "mep",
      "consulting",
      "navisworks",
    ],
    images: ["/bim/services/coordination-1.jpg"],
    reviews: [],
    averageRating: 4.8,
    reviewCount: 15,
    viewCount: 456,
    favoriteCount: 28,
    status: "published",
    featured: false,
    verified: true,
    location: {
      country: "USA",
      region: "New York",
      city: "New York",
    },
    availability: "available",
    compatibleSoftware: ["Navisworks", "Revit", "BIM 360"],
    compatibleFormats: [],
    metadata: {},
    tenantId: "tenant-1",
    createdAt: new Date("2024-08-10"),
    updatedAt: new Date("2024-11-30"),
    publishedAt: new Date("2024-08-11"),
  },
  {
    id: "listing-4",
    type: "professional",
    title: "Senior BIM Manager - Available for Projects",
    description:
      "Experienced BIM Manager available for project-based consulting. Specialized in BIM implementation, standards development, and team training.",
    category: "consulting",
    subcategory: "management",
    providerId: "bim-provider-3",
    providerName: "John Smith, BIM Specialist",
    providerRating: 4.7,
    providerVerified: true,
    pricing: {
      model: "usage-based",
      usageUnit: "hour",
      usagePrice: 200,
      currency: "USD",
      customQuote: true,
    },
    professionalData: {
      profession: "bim-manager",
      experience: 12,
      expertise: [
        "BIM Implementation",
        "Standards Development",
        "Team Training",
        "Project Management",
      ],
      certifications: ["Autodesk Certified Professional", "PMP", "BIM Level 2"],
      education: ["M.S. Civil Engineering", "B.S. Architecture"],
      portfolio: ["/portfolio/bim-implementation.jpg"],
      languages: ["English", "Spanish"],
      availability: "available",
      hourlyRate: 200,
      projectRate: 15000,
      responseTime: "12 hours",
      verifiedCredentials: true,
    },
    tags: [
      "bim-manager",
      "consulting",
      "training",
      "implementation",
      "standards",
    ],
    images: ["/bim/professionals/john-smith.jpg"],
    reviews: [],
    averageRating: 4.7,
    reviewCount: 10,
    viewCount: 234,
    favoriteCount: 15,
    status: "published",
    featured: false,
    verified: true,
    location: {
      country: "USA",
      region: "New York",
      city: "New York",
    },
    availability: "available",
    compatibleSoftware: [],
    compatibleFormats: [],
    metadata: {},
    tenantId: "tenant-1",
    createdAt: new Date("2024-07-15"),
    updatedAt: new Date("2024-12-01"),
    publishedAt: new Date("2024-07-16"),
  },
  {
    id: "listing-5",
    type: "tool",
    title: "Advanced Clash Detection Plugin for Revit",
    description:
      "Powerful plugin for automated clash detection in Revit. Features intelligent filtering, batch processing, and detailed reporting.",
    category: "software",
    subcategory: "plugin",
    providerId: "bim-provider-2",
    providerName: "Digital Construction Group",
    providerRating: 4.9,
    providerVerified: true,
    pricing: {
      model: "subscription",
      amount: 49.99,
      currency: "USD",
      subscriptionPeriod: "monthly",
      trialAvailable: true,
      trialDays: 14,
    },
    toolData: {
      toolType: "plugin",
      compatibleSoftware: ["Revit 2022", "Revit 2023", "Revit 2024"],
      version: "2.5.1",
      downloadUrl: "/tools/clash-detection-plugin.zip",
      installationGuide: "/docs/clash-plugin-install.pdf",
      apiDocumentation: "/docs/clash-plugin-api.pdf",
      support: "premium",
      updates: "automatic",
      license: "paid",
    },
    tags: ["plugin", "revit", "clash-detection", "automation", "productivity"],
    images: ["/bim/tools/clash-plugin-1.jpg", "/bim/tools/clash-plugin-2.jpg"],
    documentation: ["/bim/docs/clash-plugin-manual.pdf"],
    reviews: [],
    averageRating: 4.6,
    reviewCount: 34,
    downloadCount: 567,
    viewCount: 1234,
    favoriteCount: 89,
    status: "published",
    featured: true,
    verified: true,
    location: {
      country: "UK",
      region: "England",
      city: "London",
    },
    availability: "available",
    compatibleSoftware: ["Revit"],
    compatibleFormats: [],
    metadata: {
      lastUpdate: "2024-11-15",
      changelog: "/docs/clash-plugin-changelog.txt",
    },
    tenantId: "tenant-1",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-15"),
    publishedAt: new Date("2024-06-02"),
  },
  {
    id: "listing-6",
    type: "template",
    title: "Healthcare Facility BIM Template",
    description:
      "Comprehensive BIM template for healthcare facilities. Includes standard families, room templates, and workflow standards.",
    category: "template",
    subcategory: "project",
    providerId: "bim-provider-1",
    providerName: "BIM Solutions Inc.",
    providerRating: 4.8,
    providerVerified: true,
    pricing: {
      model: "one-time",
      amount: 149.99,
      currency: "USD",
    },
    templateData: {
      templateType: "project",
      compatibleSoftware: ["Revit 2023", "Revit 2024"],
      version: "1.2",
      downloadUrl: "/templates/healthcare-template.rte",
      previewUrl: "/templates/healthcare-preview.jpg",
      useCases: ["Hospitals", "Clinics", "Medical Centers", "Laboratories"],
      industries: ["Healthcare", "Medical"],
    },
    tags: ["template", "healthcare", "revit", "project-template", "families"],
    images: ["/bim/templates/healthcare-1.jpg"],
    reviews: [],
    averageRating: 4.4,
    reviewCount: 12,
    downloadCount: 78,
    viewCount: 345,
    favoriteCount: 23,
    status: "published",
    featured: false,
    verified: true,
    location: {
      country: "USA",
      region: "California",
      city: "San Francisco",
    },
    availability: "available",
    compatibleSoftware: ["Revit"],
    compatibleFormats: ["rte"],
    metadata: {},
    tenantId: "tenant-1",
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2024-10-15"),
    publishedAt: new Date("2024-05-21"),
  },
];
