/**
 * Self-Learning Vision Service V2
 * Continuously learns from damage photos and improves accuracy
 * Non-breaking: Works alongside existing vision service
 */

import { enhancedVisionService } from "../../enhancedVisionService";
import { knowledgeBaseService } from "@/lib/services/knowledge-base";
import { mlModelRegistry } from "@/lib/services/ml-registry";
import { eventBus } from "@/lib/services/event-bus";
import { visionLearningDatabaseAdapter } from "./visionLearningDatabaseAdapter";

// ============================================================================
// TYPES
// ============================================================================

export interface DamagePattern {
  id: string;
  patternId: string;
  name: string;
  description: string;

  // Visual characteristics
  visualFeatures: {
    damageType: string[];
    location: string[];
    severity: string[];
    shape: string[];
    color: string[];
  };

  // Context
  context: {
    area?: string; // 'loading_dock', 'storage', 'shipping'
    equipment?: string[]; // 'forklift', 'conveyor', 'handling'
    material?: string[];
    carrier?: string[];
  };

  // Learning metrics
  confidence: number; // 0-100
  occurrenceCount: number;
  accuracy: number; // How often this pattern is correct
  lastSeen: Date | string;
  firstSeen: Date | string;

  // Generated rules
  autoGeneratedRules: string[];

  // Prevention suggestions
  preventionSuggestions: string[];

  // Metadata
  tags: string[];
  tenantId?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
}

export interface LearningFeedback {
  id: string;
  patternId: string;
  photoId: string;
  damageRecordId: string;

  // User feedback
  userCorrection?: {
    originalPrediction: string;
    correctedValue: string;
    field: string; // 'damageType', 'severity', 'rootCause'
  };

  // Validation
  validated: boolean;
  validatedBy?: string;
  validatedAt?: Date | string;

  // Learning impact
  learningImpact: {
    patternConfidenceChange: number;
    ruleUpdates: string[];
    knowledgeBaseUpdates: string[];
  };

  createdAt: Date | string;
}

export interface PatternMatch {
  pattern: DamagePattern;
  matchScore: number; // 0-100
  matchedFeatures: string[];
  confidence: number;
  suggestedAction: string;
}

export interface SelfLearningConfig {
  enableAutoLearning: boolean;
  minConfidenceForLearning: number; // 0-100
  minOccurrencesForRuleGeneration: number;
  enableRuleGeneration: boolean;
  enablePreventionSuggestions: boolean;
  learningThreshold: number; // Minimum accuracy to use pattern
}

// ============================================================================
// SELF-LEARNING VISION SERVICE
// ============================================================================

class SelfLearningVisionService {
  private patterns: Map<string, DamagePattern> = new Map();
  private feedbacks: LearningFeedback[] = [];
  private patternsLoaded: boolean = false;
  private feedbacksLoaded: boolean = false;
  private defaultConfig: SelfLearningConfig = {
    enableAutoLearning: true,
    minConfidenceForLearning: 70,
    minOccurrencesForRuleGeneration: 5,
    enableRuleGeneration: true,
    enablePreventionSuggestions: true,
    learningThreshold: 75,
  };

  /**
   * Load patterns from database
   */
  private async loadPatterns(tenantId?: string): Promise<void> {
    if (this.patternsLoaded) return;

    try {
      const dbPatterns =
        await visionLearningDatabaseAdapter.getAllPatterns(tenantId);
      dbPatterns.forEach((pattern) => {
        this.patterns.set(pattern.id, pattern);
      });
      this.patternsLoaded = true;
      console.log(`✅ Loaded ${dbPatterns.length} patterns from database`);
    } catch (error) {
      console.warn("Error loading patterns from database:", error);
      this.patternsLoaded = true; // Mark as loaded to prevent infinite retries
    }
  }

  /**
   * Load feedback from database
   */
  private async loadFeedback(
    patternId?: string,
    tenantId?: string,
  ): Promise<void> {
    if (this.feedbacksLoaded && !patternId) return;

    try {
      const dbFeedback = await visionLearningDatabaseAdapter.getAllFeedback(
        patternId,
        tenantId,
      );
      // Merge with existing feedback, avoiding duplicates
      const existingIds = new Set(this.feedbacks.map((f) => f.id));
      dbFeedback.forEach((feedback) => {
        if (!existingIds.has(feedback.id)) {
          this.feedbacks.push(feedback);
        }
      });
      if (!patternId) {
        this.feedbacksLoaded = true;
      }
      if (dbFeedback.length > 0) {
        console.log(
          `✅ Loaded ${dbFeedback.length} feedback entries from database`,
        );
      }
    } catch (error) {
      console.warn("Error loading feedback from database:", error);
      if (!patternId) {
        this.feedbacksLoaded = true;
      }
    }
  }

  /**
   * Analyze damage photo with self-learning
   */
  async analyzeDamagePhoto(
    imageFile: File | string,
    context: {
      damageRecordId?: string;
      area?: string;
      equipment?: string[];
      material?: string[];
      carrier?: string;
      tenantId?: string;
    },
    config?: Partial<SelfLearningConfig>,
  ): Promise<{
    analysis: any; // Enhanced vision analysis
    patternMatches: PatternMatch[];
    suggestedRules: string[];
    preventionSuggestions: string[];
    learningMetadata: {
      patternsMatched: number;
      confidenceBoost: number;
      newPatternDetected: boolean;
    };
  }> {
    const mergedConfig = { ...this.defaultConfig, ...config };

    // Load patterns and feedback from database if not already loaded
    await this.loadPatterns(context.tenantId);
    await this.loadFeedback(undefined, context.tenantId);

    // Step 1: Get enhanced vision analysis
    const visionAnalysis = await enhancedVisionService.analyzeWithRAG(
      imageFile,
      `Damage analysis for ${context.area || "warehouse"}. Equipment: ${context.equipment?.join(", ") || "unknown"}`,
      {
        enableRAG: true,
        enableLearning: true,
        enableIndustryAnalysis: true,
        industryContext: "logistics",
      },
    );

    // Step 2: Match against learned patterns
    const patternMatches = await this.matchPatterns(visionAnalysis, context);

    // Step 3: Boost confidence based on pattern matches
    const confidenceBoost = this.calculateConfidenceBoost(patternMatches);

    // Step 4: Check if this is a new pattern
    const newPatternDetected =
      patternMatches.length === 0 &&
      visionAnalysis.analysis.qualityIssues?.length > 0;

    // Step 5: Learn from this analysis (if enabled)
    if (mergedConfig.enableAutoLearning) {
      await this.learnFromAnalysis(visionAnalysis, context, mergedConfig);
    }

    // Step 6: Generate rules (if enough occurrences)
    const suggestedRules = mergedConfig.enableRuleGeneration
      ? await this.generateRules(patternMatches, context)
      : [];

    // Step 7: Generate prevention suggestions
    const preventionSuggestions = mergedConfig.enablePreventionSuggestions
      ? await this.generatePreventionSuggestions(patternMatches, context)
      : [];

    // Step 8: Store in knowledge base
    await this.storeInKnowledgeBase(visionAnalysis, patternMatches, context);

    // Step 9: Publish learning event
    await eventBus.publish("vision.learning.analysis", {
      damageRecordId: context.damageRecordId,
      patternsMatched: patternMatches.length,
      newPatternDetected,
      confidenceBoost,
    });

    return {
      analysis: visionAnalysis,
      patternMatches,
      suggestedRules,
      preventionSuggestions,
      learningMetadata: {
        patternsMatched: patternMatches.length,
        confidenceBoost,
        newPatternDetected,
      },
    };
  }

  /**
   * Match analysis against learned patterns
   */
  private async matchPatterns(
    analysis: any,
    context: any,
  ): Promise<PatternMatch[]> {
    const matches: PatternMatch[] = [];
    const qualityIssues = analysis.analysis?.qualityIssues || [];

    for (const pattern of this.patterns.values()) {
      if (pattern.confidence < this.defaultConfig.learningThreshold) {
        continue; // Skip low-confidence patterns
      }

      let matchScore = 0;
      const matchedFeatures: string[] = [];

      // Match damage types
      for (const issue of qualityIssues) {
        if (pattern.visualFeatures.damageType.includes(issue.type)) {
          matchScore += 20;
          matchedFeatures.push(`damageType:${issue.type}`);
        }
        if (pattern.visualFeatures.severity.includes(issue.severity)) {
          matchScore += 15;
          matchedFeatures.push(`severity:${issue.severity}`);
        }
      }

      // Match context
      if (context.area && pattern.context.area === context.area) {
        matchScore += 15;
        matchedFeatures.push(`area:${context.area}`);
      }
      if (
        context.equipment &&
        pattern.context.equipment?.some((e) => context.equipment.includes(e))
      ) {
        matchScore += 15;
        matchedFeatures.push(`equipment:${context.equipment.join(",")}`);
      }
      if (
        context.carrier &&
        pattern.context.carrier?.includes(context.carrier)
      ) {
        matchScore += 10;
        matchedFeatures.push(`carrier:${context.carrier}`);
      }

      // Calculate confidence
      const confidence = Math.min(100, matchScore + pattern.confidence * 0.3);

      if (matchScore >= 40) {
        // Minimum match threshold
        matches.push({
          pattern,
          matchScore,
          matchedFeatures,
          confidence,
          suggestedAction: this.generateSuggestedAction(pattern, matchScore),
        });
      }
    }

    // Sort by match score (highest first)
    return matches.sort((a, b) => b.matchScore - a.matchScore);
  }

  /**
   * Learn from analysis
   */
  private async learnFromAnalysis(
    analysis: any,
    context: any,
    config: SelfLearningConfig,
  ): Promise<void> {
    const qualityIssues = analysis.analysis?.qualityIssues || [];

    if (qualityIssues.length === 0) {
      return; // Nothing to learn
    }

    // Extract visual features
    const visualFeatures = {
      damageType: qualityIssues.map((q: any) => q.type),
      location:
        analysis.analysis?.detectedObjects?.map((o: any) => o.location) || [],
      severity: qualityIssues.map((q: any) => q.severity),
      shape: [], // Would be extracted from image analysis
      color: [], // Would be extracted from image analysis
    };

    // Check if similar pattern exists
    const existingPattern = this.findSimilarPattern(visualFeatures, context);

    if (existingPattern) {
      // Update existing pattern
      existingPattern.occurrenceCount++;
      existingPattern.lastSeen = new Date().toISOString();
      existingPattern.confidence = Math.min(
        100,
        existingPattern.confidence + 1,
      );
      existingPattern.updatedAt = new Date().toISOString();
      this.patterns.set(existingPattern.id, existingPattern);
      // Persist to database
      await visionLearningDatabaseAdapter
        .storePattern(existingPattern)
        .catch((err) => console.warn("Failed to persist pattern update:", err));
    } else {
      // Create new pattern
      const newPattern: DamagePattern = {
        id: `pattern-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`,
        patternId: `pat-${Date.now()}`,
        name: `Pattern: ${visualFeatures.damageType[0] || "Unknown"} in ${context.area || "warehouse"}`,
        description: `Learned pattern from damage analysis`,
        visualFeatures,
        context: {
          area: context.area,
          equipment: context.equipment,
          material: context.material,
          carrier: context.carrier ? [context.carrier] : undefined,
        },
        confidence: 60, // Start with lower confidence
        occurrenceCount: 1,
        accuracy: 0, // Will be updated with feedback
        lastSeen: new Date().toISOString(),
        firstSeen: new Date().toISOString(),
        autoGeneratedRules: [],
        preventionSuggestions: [],
        tags: ["auto-learned", context.area || "warehouse"],
        tenantId: context.tenantId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      this.patterns.set(newPattern.id, newPattern);
      // Persist to database
      await visionLearningDatabaseAdapter
        .storePattern(newPattern)
        .catch((err) => console.warn("Failed to persist new pattern:", err));

      // Store in knowledge base
      await knowledgeBaseService.create({
        type: "pattern",
        category: "damage_analysis",
        content: JSON.stringify(newPattern),
        summary: newPattern.description,
        metadata: {
          patternId: newPattern.id,
          damageTypes: visualFeatures.damageType,
          area: context.area,
        },
        keywords: [
          "damage",
          "pattern",
          "learning",
          ...visualFeatures.damageType,
        ],
        searchableText: `${newPattern.name} ${newPattern.description} ${visualFeatures.damageType.join(" ")}`,
        source: "ai_learning",
        confidence: newPattern.confidence,
        verified: false,
        feedbackScore: 0,
        usageCount: 0,
        status: "active",
      });
    }
  }

  /**
   * Find similar pattern
   */
  private findSimilarPattern(
    visualFeatures: any,
    context: any,
  ): DamagePattern | undefined {
    for (const pattern of this.patterns.values()) {
      // Check visual features match
      const damageTypeMatch = visualFeatures.damageType.some((dt: string) =>
        pattern.visualFeatures.damageType.includes(dt),
      );
      const areaMatch = context.area && pattern.context.area === context.area;

      if (damageTypeMatch && areaMatch) {
        return pattern;
      }
    }
    return undefined;
  }

  /**
   * Generate rules from patterns
   */
  private async generateRules(
    patternMatches: PatternMatch[],
    context: any,
  ): Promise<string[]> {
    const rules: string[] = [];

    for (const match of patternMatches) {
      const pattern = match.pattern;

      if (
        pattern.occurrenceCount >=
        this.defaultConfig.minOccurrencesForRuleGeneration
      ) {
        // Generate rule
        const rule = this.createRuleFromPattern(pattern);
        if (rule && !pattern.autoGeneratedRules.includes(rule)) {
          pattern.autoGeneratedRules.push(rule);
          rules.push(rule);
          this.patterns.set(pattern.id, pattern);
          // Persist to database
          await visionLearningDatabaseAdapter
            .storePattern(pattern)
            .catch((err) =>
              console.warn("Failed to persist pattern update:", err),
            );
        }
      }
    }

    return rules;
  }

  /**
   * Create rule from pattern
   */
  private createRuleFromPattern(pattern: DamagePattern): string | null {
    const conditions: string[] = [];

    // Area condition
    if (pattern.context.area) {
      conditions.push(`area == "${pattern.context.area}"`);
    }

    // Equipment condition
    if (pattern.context.equipment && pattern.context.equipment.length > 0) {
      conditions.push(
        `equipment in [${pattern.context.equipment.map((e) => `"${e}"`).join(", ")}]`,
      );
    }

    // Damage type condition
    if (pattern.visualFeatures.damageType.length > 0) {
      conditions.push(
        `damageType in [${pattern.visualFeatures.damageType.map((dt) => `"${dt}"`).join(", ")}]`,
      );
    }

    if (conditions.length === 0) {
      return null;
    }

    const rule = `IF ${conditions.join(" AND ")} THEN likelyRootCause = "${pattern.name}" (confidence: ${pattern.confidence}%)`;

    return rule;
  }

  /**
   * Generate prevention suggestions
   */
  private async generatePreventionSuggestions(
    patternMatches: PatternMatch[],
    context: any,
  ): Promise<string[]> {
    const suggestions: string[] = [];

    for (const match of patternMatches) {
      const pattern = match.pattern;

      // Generate suggestions based on pattern
      if (pattern.context.area === "loading_dock") {
        suggestions.push(
          "Review loading dock procedures and equipment handling",
        );
      }
      if (pattern.context.equipment?.includes("forklift")) {
        suggestions.push("Provide additional forklift operator training");
        suggestions.push("Review forklift maintenance schedule");
      }
      if (pattern.visualFeatures.damageType.includes("crush")) {
        suggestions.push("Review stacking procedures and weight limits");
      }
      if (pattern.visualFeatures.damageType.includes("water_damage")) {
        suggestions.push("Review storage location weather protection");
      }
    }

    // Remove duplicates
    return Array.from(new Set(suggestions));
  }

  /**
   * Store in knowledge base
   */
  private async storeInKnowledgeBase(
    analysis: any,
    patternMatches: PatternMatch[],
    context: any,
  ): Promise<void> {
    const knowledgeEntry = {
      type: "analysis" as const,
      category: "damage_analysis" as const,
      content: JSON.stringify({
        analysis,
        patternMatches,
        context,
      }),
      summary: `Damage analysis with ${patternMatches.length} pattern matches`,
      metadata: {
        patternMatches: patternMatches.length,
        damageTypes:
          analysis.analysis?.qualityIssues?.map((q: any) => q.type) || [],
        area: context.area,
      },
      keywords: [
        "damage",
        "analysis",
        "vision",
        ...(analysis.analysis?.qualityIssues?.map((q: any) => q.type) || []),
      ],
      searchableText: `Damage analysis ${context.area || ""} ${analysis.analysis?.description || ""}`,
      source: "ai_vision" as const,
      confidence: patternMatches.length > 0 ? patternMatches[0].confidence : 70,
      verified: false,
      feedbackScore: 0,
      usageCount: 0,
      status: "active" as const,
    };

    await knowledgeBaseService.create(knowledgeEntry);
  }

  /**
   * Process user feedback
   */
  async processFeedback(feedback: LearningFeedback): Promise<void> {
    this.feedbacks.push(feedback);
    // Persist to database
    await visionLearningDatabaseAdapter
      .storeFeedback(feedback)
      .catch((err) => console.warn("Failed to persist feedback:", err));

    // Load pattern if not in memory
    let pattern = this.patterns.get(feedback.patternId);
    if (!pattern) {
      pattern = await visionLearningDatabaseAdapter.getPattern(
        feedback.patternId,
        (feedback as any).tenantId,
      );
      if (pattern) {
        this.patterns.set(pattern.id, pattern);
      }
    }
    if (!pattern) {
      return;
    }

    // Update pattern based on feedback
    if (feedback.userCorrection) {
      // User corrected prediction
      pattern.accuracy = Math.max(0, pattern.accuracy - 5); // Decrease accuracy
      pattern.confidence = Math.max(0, pattern.confidence - 2); // Decrease confidence
    } else if (feedback.validated) {
      // User validated prediction
      pattern.accuracy = Math.min(100, pattern.accuracy + 5); // Increase accuracy
      pattern.confidence = Math.min(100, pattern.confidence + 2); // Increase confidence
    }

    pattern.updatedAt = new Date().toISOString();
    this.patterns.set(pattern.id, pattern);
    // Persist to database
    await visionLearningDatabaseAdapter
      .storePattern(pattern)
      .catch((err) =>
        console.warn("Failed to persist pattern update from feedback:", err),
      );

    // Update knowledge base
    await knowledgeBaseService.processFeedback({
      knowledgeId: `pattern-${pattern.id}`,
      type: feedback.validated ? "positive" : "negative",
      comment: feedback.userCorrection
        ? `Correction: ${feedback.userCorrection.originalPrediction} → ${feedback.userCorrection.correctedValue}`
        : "Validated",
      correctedContent: feedback.userCorrection?.correctedValue,
    });

    // Publish feedback event
    await eventBus.publish("vision.learning.feedback", {
      patternId: feedback.patternId,
      validated: feedback.validated,
      impact: feedback.learningImpact,
    });
  }

  /**
   * Get learned patterns
   */
  async getPatterns(tenantId?: string): Promise<DamagePattern[]> {
    // Load from database if not already loaded
    await this.loadPatterns(tenantId);
    const patterns = Array.from(this.patterns.values());
    return tenantId
      ? patterns.filter((p) => p.tenantId === tenantId)
      : patterns;
  }

  /**
   * Get pattern by ID
   */
  getPattern(patternId: string): DamagePattern | undefined {
    return this.patterns.get(patternId);
  }

  /**
   * Calculate confidence boost from pattern matches
   */
  private calculateConfidenceBoost(patternMatches: PatternMatch[]): number {
    if (patternMatches.length === 0) {
      return 0;
    }

    // Average match score of top 3 matches
    const topMatches = patternMatches.slice(0, 3);
    const avgMatchScore =
      topMatches.reduce((sum, m) => sum + m.matchScore, 0) / topMatches.length;

    // Boost is proportional to match score (max 20 points)
    return Math.min(20, avgMatchScore * 0.2);
  }

  /**
   * Generate suggested action
   */
  private generateSuggestedAction(
    pattern: DamagePattern,
    matchScore: number,
  ): string {
    if (matchScore >= 80) {
      return `High confidence match: ${pattern.name}. Apply prevention: ${pattern.preventionSuggestions[0] || "Review procedures"}`;
    } else if (matchScore >= 60) {
      return `Moderate match: ${pattern.name}. Consider reviewing similar cases.`;
    } else {
      return `Low match: ${pattern.name}. Manual review recommended.`;
    }
  }
}

// ============================================================================
// SINGLETON EXPORT
// ============================================================================

export const selfLearningVisionService = new SelfLearningVisionService();
export default selfLearningVisionService;
