/**
 * Vision Database Service
 * Prisma-based database service for AI Vision Module
 * Provides full CRUD operations with tenant isolation
 * Integrated with BlueDXP platform architecture
 */

import { prisma } from "@/lib/services/database/prismaClient";
import { VisionAnalysisResult } from "../visionService";
import { eventBus } from "@/lib/services/event-store";
import { visionEventIntegration } from "./visionEventIntegration";

// ============================================================================
// TYPES
// ============================================================================

export interface VisionAnalysisCreate {
  analysisId: string;
  tenantId?: string;
  userId?: string;
  imageUrl?: string;
  thumbnailUrl?: string;
  fileUrl?: string;
  fileName?: string;
  fileSize?: number;
  mimeType?: string;
  imageSize?: { width: number; height: number };
  analysis: any; // VisionAnalysisResult['analysis']
  analysisMode?: string;
  provider?: string;
  model?: string;
  processingTime?: number;
  context?: string;
  module?: string;
  moduleContext?: any;
  totalIssues?: number;
  criticalIssues?: number;
  complianceScore?: number;
  isCompliant?: boolean;
  relatedRecordId?: string;
  relatedRecordType?: string;
  metadata?: any;
  tags?: string[];
}

export interface VisionAnalysisUpdate {
  analysis?: any;
  totalIssues?: number;
  criticalIssues?: number;
  complianceScore?: number;
  isCompliant?: boolean;
  metadata?: any;
  tags?: string[];
}

export interface VisionPatternCreate {
  patternId: string;
  tenantId?: string;
  name: string;
  description?: string;
  visualFeatures?: any;
  context?: any;
  confidence?: number;
  occurrenceCount?: number;
  accuracy?: number;
  firstSeen?: Date;
  lastSeen?: Date;
  autoGeneratedRules?: any;
  preventionSuggestions?: any;
  tags?: any;
  analysisId?: string;
}

export interface VisionFeedbackCreate {
  tenantId?: string;
  userId?: string;
  patternId?: string;
  analysisId?: string;
  photoId?: string;
  recordId?: string;
  recordType?: string;
  userCorrection?: any;
  validated?: boolean;
  validatedBy?: string;
  validatedAt?: Date;
  learningImpact?: any;
  metadata?: any;
}

// ============================================================================
// VISION DATABASE SERVICE
// ============================================================================

class VisionDatabaseService {
  /**
   * Create vision analysis
   */
  async createAnalysis(data: VisionAnalysisCreate) {
    try {
      const analysis = await prisma.visionAnalysis.create({
        data: {
          analysisId: data.analysisId,
          tenantId: data.tenantId,
          userId: data.userId,
          imageUrl: data.imageUrl,
          thumbnailUrl: data.thumbnailUrl,
          fileUrl: data.fileUrl,
          fileName: data.fileName,
          fileSize: data.fileSize,
          mimeType: data.mimeType,
          imageSize: data.imageSize as any,
          analysis: data.analysis as any,
          analysisMode: data.analysisMode,
          provider: data.provider,
          model: data.model,
          processingTime: data.processingTime,
          context: data.context,
          module: data.module,
          moduleContext: data.moduleContext as any,
          totalIssues: data.totalIssues || 0,
          criticalIssues: data.criticalIssues || 0,
          complianceScore: data.complianceScore,
          isCompliant: data.isCompliant ?? true,
          relatedRecordId: data.relatedRecordId,
          relatedRecordType: data.relatedRecordType,
          metadata: data.metadata as any,
          tags: data.tags || [],
        },
      });

      // Emit events
      await eventBus.publish({
        type: "ai.vision.analysis.created",
        aggregateId: analysis.id,
        aggregateType: "VisionAnalysis",
        payload: {
          analysisId: analysis.analysisId,
          tenantId: analysis.tenantId,
          module: analysis.module,
          totalIssues: analysis.totalIssues,
          isCompliant: analysis.isCompliant,
        },
        metadata: {
          userId: data.userId,
          timestamp: new Date().toISOString(),
        },
      });

      // Publish analysis completed event
      await visionEventIntegration.publishAnalysisCompleted(
        analysis.analysisId,
        analysis.tenantId || "",
        {
          totalIssues: analysis.totalIssues,
          criticalIssues: analysis.criticalIssues,
          isCompliant: analysis.isCompliant,
          module: analysis.module,
        },
      );

      // Check for compliance violations
      if (analysis.analysis && typeof analysis.analysis === "object") {
        const analysisData = analysis.analysis as any;
        if (
          analysisData.complianceIssues &&
          Array.isArray(analysisData.complianceIssues) &&
          analysisData.complianceIssues.length > 0
        ) {
          await visionEventIntegration.publishComplianceViolation(
            analysis.analysisId,
            analysis.tenantId || "",
            analysisData.complianceIssues,
          );
        }
      }

      // Create history entry
      await this.createHistory({
        analysisId: analysis.id,
        tenantId: data.tenantId,
        userId: data.userId,
        action: "created",
        metadata: { source: "api" },
      });

      return analysis;
    } catch (error) {
      console.error("Error creating vision analysis:", error);
      throw error;
    }
  }

  /**
   * Get vision analysis by ID
   */
  async getAnalysisById(id: string, tenantId?: string) {
    try {
      const analysis = await prisma.visionAnalysis.findFirst({
        where: {
          OR: [{ id }, { analysisId: id }],
          ...(tenantId ? { tenantId } : {}),
        },
        include: {
          patterns: {
            take: 10,
            orderBy: { lastSeen: "desc" },
          },
          feedback: {
            take: 5,
            orderBy: { createdAt: "desc" },
          },
          history: {
            take: 20,
            orderBy: { createdAt: "desc" },
          },
        },
      });

      return analysis;
    } catch (error) {
      console.error("Error getting vision analysis:", error);
      throw error;
    }
  }

  /**
   * Get vision analysis by analysisId
   */
  async getAnalysisByAnalysisId(analysisId: string, tenantId?: string) {
    return this.getAnalysisById(analysisId, tenantId);
  }

  /**
   * List vision analyses with filters
   */
  async listAnalyses(options: {
    tenantId?: string;
    userId?: string;
    module?: string;
    relatedRecordType?: string;
    isCompliant?: boolean;
    limit?: number;
    offset?: number;
    orderBy?: "createdAt" | "updatedAt" | "totalIssues";
    order?: "asc" | "desc";
  }) {
    try {
      const {
        tenantId,
        userId,
        module,
        relatedRecordType,
        isCompliant,
        limit = 50,
        offset = 0,
        orderBy = "createdAt",
        order = "desc",
      } = options;

      const analyses = await prisma.visionAnalysis.findMany({
        where: {
          ...(tenantId ? { tenantId } : {}),
          ...(userId ? { userId } : {}),
          ...(module ? { module } : {}),
          ...(relatedRecordType ? { relatedRecordType } : {}),
          ...(isCompliant !== undefined ? { isCompliant } : {}),
        },
        take: limit,
        skip: offset,
        orderBy: {
          [orderBy]: order,
        },
        include: {
          patterns: {
            take: 3,
            orderBy: { lastSeen: "desc" },
          },
        },
      });

      const total = await prisma.visionAnalysis.count({
        where: {
          ...(tenantId ? { tenantId } : {}),
          ...(userId ? { userId } : {}),
          ...(module ? { module } : {}),
          ...(relatedRecordType ? { relatedRecordType } : {}),
          ...(isCompliant !== undefined ? { isCompliant } : {}),
        },
      });

      return {
        analyses,
        total,
        limit,
        offset,
      };
    } catch (error) {
      console.error("Error listing vision analyses:", error);
      throw error;
    }
  }

  /**
   * Update vision analysis
   */
  async updateAnalysis(
    id: string,
    data: VisionAnalysisUpdate,
    tenantId?: string,
    userId?: string,
  ) {
    try {
      const existing = await prisma.visionAnalysis.findFirst({
        where: {
          OR: [{ id }, { analysisId: id }],
          ...(tenantId ? { tenantId } : {}),
        },
      });

      if (!existing) {
        throw new Error("Vision analysis not found");
      }

      const previousState = {
        analysis: existing.analysis,
        totalIssues: existing.totalIssues,
        criticalIssues: existing.criticalIssues,
        complianceScore: existing.complianceScore,
        isCompliant: existing.isCompliant,
      };

      const analysis = await prisma.visionAnalysis.update({
        where: { id: existing.id },
        data: {
          ...(data.analysis !== undefined
            ? { analysis: data.analysis as any }
            : {}),
          ...(data.totalIssues !== undefined
            ? { totalIssues: data.totalIssues }
            : {}),
          ...(data.criticalIssues !== undefined
            ? { criticalIssues: data.criticalIssues }
            : {}),
          ...(data.complianceScore !== undefined
            ? { complianceScore: data.complianceScore }
            : {}),
          ...(data.isCompliant !== undefined
            ? { isCompliant: data.isCompliant }
            : {}),
          ...(data.metadata !== undefined
            ? { metadata: data.metadata as any }
            : {}),
          ...(data.tags !== undefined ? { tags: data.tags } : {}),
        },
      });

      // Emit event
      await eventBus.publish({
        type: "ai.vision.analysis.updated",
        aggregateId: analysis.id,
        aggregateType: "VisionAnalysis",
        payload: {
          analysisId: analysis.analysisId,
          tenantId: analysis.tenantId,
          changes: data,
        },
        metadata: {
          userId,
          timestamp: new Date().toISOString(),
        },
      });

      // Create history entry
      await this.createHistory({
        analysisId: analysis.id,
        tenantId: tenantId || existing.tenantId || undefined,
        userId,
        action: "updated",
        changes: data,
        previousState,
        metadata: { source: "api" },
      });

      return analysis;
    } catch (error) {
      console.error("Error updating vision analysis:", error);
      throw error;
    }
  }

  /**
   * Delete vision analysis
   */
  async deleteAnalysis(id: string, tenantId?: string, userId?: string) {
    try {
      const existing = await prisma.visionAnalysis.findFirst({
        where: {
          OR: [{ id }, { analysisId: id }],
          ...(tenantId ? { tenantId } : {}),
        },
      });

      if (!existing) {
        throw new Error("Vision analysis not found");
      }

      await prisma.visionAnalysis.delete({
        where: { id: existing.id },
      });

      // Emit event
      await eventBus.publish({
        type: "ai.vision.analysis.deleted",
        aggregateId: existing.id,
        aggregateType: "VisionAnalysis",
        payload: {
          analysisId: existing.analysisId,
          tenantId: existing.tenantId,
        },
        metadata: {
          userId,
          timestamp: new Date().toISOString(),
        },
      });

      return { success: true };
    } catch (error) {
      console.error("Error deleting vision analysis:", error);
      throw error;
    }
  }

  /**
   * Create or update vision pattern
   */
  async upsertPattern(data: VisionPatternCreate) {
    try {
      const pattern = await prisma.visionPattern.upsert({
        where: { patternId: data.patternId },
        update: {
          name: data.name,
          description: data.description,
          visualFeatures: data.visualFeatures as any,
          context: data.context as any,
          confidence: data.confidence,
          occurrenceCount: data.occurrenceCount,
          accuracy: data.accuracy,
          lastSeen: data.lastSeen || new Date(),
          autoGeneratedRules: data.autoGeneratedRules as any,
          preventionSuggestions: data.preventionSuggestions as any,
          tags: data.tags as any,
          analysisId: data.analysisId,
          updatedAt: new Date(),
        },
        create: {
          patternId: data.patternId,
          tenantId: data.tenantId,
          name: data.name,
          description: data.description,
          visualFeatures: data.visualFeatures as any,
          context: data.context as any,
          confidence: data.confidence || 0,
          occurrenceCount: data.occurrenceCount || 0,
          accuracy: data.accuracy || 0,
          firstSeen: data.firstSeen || new Date(),
          lastSeen: data.lastSeen || new Date(),
          autoGeneratedRules: data.autoGeneratedRules as any,
          preventionSuggestions: data.preventionSuggestions as any,
          tags: data.tags as any,
          analysisId: data.analysisId,
        },
      });

      // Emit event
      await eventBus.publish({
        type: "ai.vision.pattern.updated",
        aggregateId: pattern.id,
        aggregateType: "VisionPattern",
        payload: {
          patternId: pattern.patternId,
          tenantId: pattern.tenantId,
          confidence: pattern.confidence,
          occurrenceCount: pattern.occurrenceCount,
        },
        metadata: {
          timestamp: new Date().toISOString(),
        },
      });

      return pattern;
    } catch (error) {
      console.error("Error upserting vision pattern:", error);
      throw error;
    }
  }

  /**
   * Get vision patterns
   */
  async getPatterns(options: {
    tenantId?: string;
    analysisId?: string;
    limit?: number;
    offset?: number;
  }) {
    try {
      const { tenantId, analysisId, limit = 50, offset = 0 } = options;

      const patterns = await prisma.visionPattern.findMany({
        where: {
          ...(tenantId ? { tenantId } : {}),
          ...(analysisId ? { analysisId } : {}),
        },
        take: limit,
        skip: offset,
        orderBy: {
          lastSeen: "desc",
        },
        include: {
          feedback: {
            take: 3,
            orderBy: { createdAt: "desc" },
          },
        },
      });

      return patterns;
    } catch (error) {
      console.error("Error getting vision patterns:", error);
      throw error;
    }
  }

  /**
   * Create vision feedback
   */
  async createFeedback(data: VisionFeedbackCreate) {
    try {
      const feedback = await prisma.visionFeedback.create({
        data: {
          tenantId: data.tenantId,
          userId: data.userId,
          patternId: data.patternId,
          analysisId: data.analysisId,
          photoId: data.photoId,
          recordId: data.recordId,
          recordType: data.recordType,
          userCorrection: data.userCorrection as any,
          validated: data.validated || false,
          validatedBy: data.validatedBy,
          validatedAt: data.validatedAt,
          learningImpact: data.learningImpact as any,
          metadata: data.metadata as any,
        },
      });

      // Emit event
      await eventBus.publish({
        type: "ai.vision.feedback.created",
        aggregateId: feedback.id,
        aggregateType: "VisionFeedback",
        payload: {
          feedbackId: feedback.id,
          patternId: feedback.patternId,
          analysisId: feedback.analysisId,
          validated: feedback.validated,
        },
        metadata: {
          userId: data.userId,
          timestamp: new Date().toISOString(),
        },
      });

      return feedback;
    } catch (error) {
      console.error("Error creating vision feedback:", error);
      throw error;
    }
  }

  /**
   * Create history entry
   */
  async createHistory(data: {
    analysisId: string;
    tenantId?: string;
    userId?: string;
    action: string;
    changes?: any;
    previousState?: any;
    metadata?: any;
  }) {
    try {
      const history = await prisma.visionHistory.create({
        data: {
          tenantId: data.tenantId,
          userId: data.userId,
          analysisId: data.analysisId,
          action: data.action,
          changes: data.changes as any,
          previousState: data.previousState as any,
          metadata: data.metadata as any,
        },
      });

      return history;
    } catch (error) {
      console.error("Error creating vision history:", error);
      // Don't throw - history is non-critical
      return null;
    }
  }

  /**
   * Get analytics/metrics
   */
  async getMetrics(options: {
    tenantId?: string;
    startDate?: Date;
    endDate?: Date;
    period?: "daily" | "weekly" | "monthly";
  }) {
    try {
      const { tenantId, startDate, endDate, period = "daily" } = options;

      // Get analyses in date range
      const analyses = await prisma.visionAnalysis.findMany({
        where: {
          ...(tenantId ? { tenantId } : {}),
          ...(startDate || endDate
            ? {
                createdAt: {
                  ...(startDate ? { gte: startDate } : {}),
                  ...(endDate ? { lte: endDate } : {}),
                },
              }
            : {}),
        },
        select: {
          totalIssues: true,
          criticalIssues: true,
          complianceScore: true,
          isCompliant: true,
          processingTime: true,
          module: true,
          analysisMode: true,
          createdAt: true,
        },
      });

      // Calculate metrics
      const totalAnalyses = analyses.length;
      const totalIssues = analyses.reduce((sum, a) => sum + a.totalIssues, 0);
      const criticalIssues = analyses.reduce(
        (sum, a) => sum + a.criticalIssues,
        0,
      );
      const averageScore =
        analyses.filter((a) => a.complianceScore !== null).length > 0
          ? analyses
              .filter((a) => a.complianceScore !== null)
              .reduce((sum, a) => sum + (a.complianceScore || 0), 0) /
            analyses.filter((a) => a.complianceScore !== null).length
          : null;
      const averageTime =
        analyses.filter((a) => a.processingTime !== null).length > 0
          ? analyses
              .filter((a) => a.processingTime !== null)
              .reduce((sum, a) => sum + (a.processingTime || 0), 0) /
            analyses.filter((a) => a.processingTime !== null).length
          : null;

      // By module
      const byModule: Record<string, { count: number; issues: number }> = {};
      analyses.forEach((a) => {
        const moduleName = a.module || "unknown";
        if (!byModule[moduleName]) {
          byModule[moduleName] = { count: 0, issues: 0 };
        }
        byModule[moduleName].count++;
        byModule[moduleName].issues += a.totalIssues;
      });

      // By analysis type
      const byAnalysisType: Record<string, number> = {};
      analyses.forEach((a) => {
        const type = a.analysisMode || "standard";
        byAnalysisType[type] = (byAnalysisType[type] || 0) + 1;
      });

      return {
        totalAnalyses,
        totalIssues,
        criticalIssues,
        averageScore: averageScore ? Number(averageScore.toFixed(2)) : null,
        averageTime: averageTime ? Math.round(averageTime) : null,
        totalProcessingTime: analyses.reduce(
          (sum, a) => sum + (a.processingTime || 0),
          0,
        ),
        byModule,
        byAnalysisType,
      };
    } catch (error) {
      console.error("Error getting vision metrics:", error);
      throw error;
    }
  }
}

// Export singleton
export const visionDatabaseService = new VisionDatabaseService();
export default visionDatabaseService;
